export enum UniswapEventName {
  BalancesReport = 'Balances Report',
  BalancesReportPerChain = 'Balances Report Per Chain',
  BlockaidFeesMismatch = 'Blockaid Fees Mismatch',
  ConversionEventSubmitted = 'Conversion Event Submitted',
  DataReportSubmitted = 'Data Report Submitted',
  DelegationDetected = 'Delegation Detected',
  ExperimentQualifyingEvent = 'Experiment Qualifying Event',
  LowNetworkTokenInfoModalOpened = 'Low Network Token Info Modal Opened',
  LpIncentiveCollectRewardsButtonClicked = 'LP Incentive Collect Rewards Button Clicked',
  LpIncentiveCollectRewardsErrorThrown = 'LP Incentive Collect Rewards Error Thrown',
  LpIncentiveCollectRewardsRetry = 'LP Incentive Collect Rewards Retry',
  LpIncentiveCollectRewardsSuccess = 'LP Incentive Collect Rewards Success',
  LpIncentiveLearnMoreCtaClicked = 'LP Incentive Learn More CTA Clicked',
  SmartWalletMismatchDetected = 'Smart Wallet Mismatch Detected',
  SpamReportSubmitted = 'Spam Report Submitted',
  TokenSelected = 'Token Selected',
  TooltipOpened = 'Tooltip Opened',
  // alphabetize additional values.
}
