export enum UniswapEventName {
  AuctionFilterSelected = 'Auction Filter Selected',
  BalancesReport = 'Balances Report',
  BalancesReportPerChain = 'Balances Report Per Chain',
  BlockaidFeesMismatch = 'Blockaid Fees Mismatch',
  ContextMenuClosed = 'Context Menu Closed',
  ContextMenuItemClicked = 'Context Menu Item Clicked',
  ContextMenuOpened = 'Context Menu Opened',
  ConversionEventSubmitted = 'Conversion Event Submitted',
  DataReportSubmitted = 'Data Report Submitted',
  DelegationDetected = 'Delegation Detected',
  ExperimentQualifyingEvent = 'Experiment Qualifying Event',
  LowNetworkTokenInfoModalOpened = 'Low Network Token Info Modal Opened',
  LpIncentiveCollectRewardsButtonClicked = 'LP Incentive Collect Rewards Button Clicked',
  LpIncentiveCollectRewardsErrorThrown = 'LP Incentive Collect Rewards Error Thrown',
  LpIncentiveCollectRewardsRetry = 'LP Incentive Collect Rewards Retry',
  LpIncentiveCollectRewardsSuccess = 'LP Incentive Collect Rewards Success',
  LpIncentiveLearnMoreCtaClicked = 'LP Incentive Learn More CTA Clicked',
  MultichainExploreMetrics = 'Multichain Explore Metrics',
  MultichainPortfolioMetrics = 'Multichain Portfolio Metrics',
  MultichainSearchMetrics = 'Multichain Search Metrics',
  NetworkFilterSelected = 'Network Filter Selected',
  PnlCoverageReport = 'PnL Coverage Report',
  PnlPortfolioReport = 'PnL Portfolio Report',
  PnlTokenReport = 'PnL Token Report',
  SmartWalletMismatchDetected = 'Smart Wallet Mismatch Detected',
  SpamReportSubmitted = 'Spam Report Submitted',
  TokenSelected = 'Token Selected',
  TooltipOpened = 'Tooltip Opened',
  // alphabetize additional values.
}
