version: 2
updates:
  - package-ecosystem: npm
    # Files stored in repository root
    directory: '/'
    schedule:
      interval: 'daily'
    allow:
      - dependency-name: '@kinetix/default-token-list'
      - dependency-name: '@kinetix/token-lists'
    reviewers:
      - 'Uniswap/dependabot-reviewers'
