ignore:
  - "**/generated/**/*"
  - "**/generated/*"
  - "**/cypress/**/*"
  - "cypress/**/*"
  - "**/instrumented/**/*"
  - "**/styles/**/*"
  - "styles/**/*"
  - "**/constants/**/*"
  - "constants/**/*"

flag_management:
  default_rules:
    statuses:
      - type: project
        target: auto
        threshold: 1%
        if_ci_failed: error
      - type: patch
        target: 80%
  individual_flags:
    - name: e2e-tests
      statuses:
        - type: patch
          target: 0%
