module.exports = {
  globals: {
    ALCHEMY_API_KEY: 123,
    AMPLITUDE_EXPERIMENTS_DEPLOYMENT_KEY: 123,
    APPSFLYER_API_KEY: 'key',
    APPSFLYER_APP_ID: 123,
    MOONPAY_API_KEY: 123,
    MOONPAY_API_URL: 'https://api.moonpay.com',
    MOONPAY_WIDGET_API_URL: 'https://api.moonpay.com',
    INFURA_PROJECT_ID: 123,
    ONESIGNAL_APP_ID: 123,
    SENTRY_DSN: 'http://sentry.com',
    SHAKE_CLIENT_ID: 123,
    SHAKE_CLIENT_SECRET: 123,
    STATSIG_PROXY_URL: 'https://api.statsig.com',
    UNISWAP_API_KEY: 123,
    UNISWAP_API_BASE_URL: 'https://api.uniswap.org',
    WALLETCONNECT_PROJECT_ID: 123,
    QUICKNODE_BNB_RPC_URL: 'https://api.uniswap.org',
  },
}