process.env.TZ = 'America/New_York';

module.exports = {
  globals: {
    ALCHEMY_API_KEY: 'key',
    AMPLITUDE_EXPERIMENTS_DEPLOYMENT_KEY: 'key',
    APPSFLYER_API_KEY: 'key',
    APPSFLYER_APP_ID: 123,
    MELD_API_KEY: 'key',
    MELD_API_VERSION: 'version',
    MELD_API_URL: 'https://api-sb.meld.io',
    MOONPAY_API_KEY: 'key',
    MOONPAY_API_URL: 'https://api.moonpay.com',
    MOONPAY_WIDGET_API_URL: 'https://api.moonpay.com',
    INFURA_PROJECT_ID: 123,
    ONESIGNAL_APP_ID: 123,
    QUICKNODE_BNB_RPC_URL: 'https://api.uniswap.org',
    SENTRY_DSN: 'http://sentry.com',
    SHAKE_CLIENT_ID: 123,
    SHAKE_CLIENT_SECRET: 123,
    SIMPLEHASH_API_KEY: 'key',
    SIMPLEHASH_API_URL: 'https://api.simplehash.com',
    STATSIG_PROXY_URL: 'https://api.statsig.com',
    TRADING_API_KEY: 'key',
    UNISWAP_API_KEY: 'key',
    UNISWAP_API_BASE_URL: 'https://api.uniswap.org',
    UNISWAP_APP_URL: 'https://app.uniswap.org',
    WALLETCONNECT_PROJECT_ID: 123,
    UNITAGS_API_URL: 'https://api.uniswap.org/unitags',
  },
};
