export const LAUNCH_MODAL_DESKTOP_MAX_WIDTH = 520
export const LAUNCH_MODAL_DESKTOP_MAX_HEIGHT = 320
export const LAUNCH_MODAL_MOBILE_MAX_HEIGHT = 564
export const LAUNCH_MODAL_MOBILE_MAX_IMAGE_HEIGHT = 392
