import { MonitorDefinition } from '../../types'

export const devPortalAuthMonitors: MonitorDefinition[] = [
  {
    id: 'dev-portal_auth_failure_rate',
    name: 'Auth Failure Rate on dev-portal',
    type: 'log alert',
    query: `logs("service:dev-portal (message:*auth*failed OR message:*session*failed)").index("*").rollup("count").last("15m") > 20`,
    alertBody: 'Auth failure log count for dev-portal has exceeded 20 in the last 15 minutes.',
    recoveryBody: 'Auth failure rate for dev-portal has recovered.',
    team: 'dev-portal',
    priority: 3,
    thresholds: { critical: 20 },
    logQuery: 'service:dev-portal',
    runbookUrl: 'https://www.notion.so/uniswap/dev-portal-runbook',
    readmeUrl: 'https://github.com/Uniswap/universe/tree/main/apps/dev-portal',
    dashboards: [],
    enablePaging: false,
    onMissingData: 'show_no_data',
    prodOnly: true,
  },
  {
    id: 'dev-portal_session_conflict_spike',
    name: 'Session Conflict Spike on dev-portal',
    type: 'log alert',
    query: `logs("service:dev-portal message:*conflict").index("*").rollup("count").last("15m") > 10`,
    alertBody: 'Session conflict log count for dev-portal has exceeded 10 in the last 15 minutes.',
    recoveryBody: 'Session conflict rate for dev-portal has recovered.',
    team: 'dev-portal',
    priority: 3,
    thresholds: { critical: 10 },
    logQuery: 'service:dev-portal',
    runbookUrl: 'https://www.notion.so/uniswap/dev-portal-runbook',
    readmeUrl: 'https://github.com/Uniswap/universe/tree/main/apps/dev-portal',
    dashboards: [],
    enablePaging: false,
    onMissingData: 'show_no_data',
    prodOnly: true,
  },
]
