export const MENU_CLOSE_DELAY_MS = 300
export const NUMBER_OF_RESULTS_SHORT = 3
export const NUMBER_OF_RESULTS_ALL_TAB = 6
export const NUMBER_OF_RESULTS_MEDIUM = 8
export const NUMBER_OF_RESULTS_LONG = 15
