/**
 * The Tailwind utility-candidate manifest for the workbench TouchableArea
 * parity page.
 *
 * `TouchableAreaCompat` computes its className at runtime, so Tailwind's
 * static scanner never sees the candidates. The parity matrix is finite and
 * deterministic, so the exact utility set is enumerated here — every case the
 * board renders, its forced pseudo-state pairs, its forced-disabled pairs,
 * and the group containers `$group-*` cases are wrapped in — and checked into
 * the workbench as `touchable-parity.classes.txt` (referenced from `app.css`
 * via `@source`).
 *
 * The workbench `generate:option-classes` script writes the file; the
 * regenerate-and-diff test in `class-manifest.test.ts` fails whenever the
 * checked-in manifest drifts from this enumeration.
 */
// Relative cross-package import: a package dep edge tailwind → mycelium would cycle (mycelium already depends on tailwind).
// nx-ignore-next-line
import { parseGroupStateProp } from '../../../../mycelium/src/compat/group'
// nx-ignore-next-line
import { flexCompatClassName } from '../../../../mycelium/src/flex-compat/compile'
// nx-ignore-next-line
import {
  touchableAreaCompatClassName,
  type TouchableAreaCompatProps,
} from '../../../../mycelium/src/touchable-area/compile'
import { buildMatrix } from './matrix'

const PSEUDO_FORCE_STYLES = {
  hoverStyle: 'hover',
  pressStyle: 'press',
  focusStyle: 'focus',
  focusVisibleStyle: 'focusVisible',
  focusWithinStyle: 'focusWithin',
} as const

/** The group container a `$group-*` case renders inside, via the shared group parser. */
function groupContainerName(props: TouchableAreaCompatProps): string | boolean | undefined {
  for (const key of Object.keys(props)) {
    const parts = parseGroupStateProp(key)
    if (parts !== undefined) {
      return parts.name ?? true
    }
  }
  return undefined
}

/**
 * Everything the board renders for one matrix case: the case itself, a
 * forced-state pair per pseudo pool, and a forced-disabled pair for
 * disabledStyle cases (`disabled` also changes the compiled base pool here,
 * unlike Flex).
 */
function renderedPropVariants(props: TouchableAreaCompatProps): TouchableAreaCompatProps[] {
  const variants: TouchableAreaCompatProps[] = [props]
  for (const [pseudoKey, forceStyle] of Object.entries(PSEUDO_FORCE_STYLES)) {
    if (props[pseudoKey as keyof typeof PSEUDO_FORCE_STYLES] !== undefined) {
      variants.push({ ...props, forceStyle })
    }
  }
  if (props.disabledStyle !== undefined && props.disabled !== true) {
    variants.push({ ...props, disabled: true })
  }
  return variants
}

/** Sorted, de-duplicated utility candidates for the whole parity board. */
export function buildTouchableAreaParityClassManifest(): string[] {
  const classes = new Set<string>()
  const addClasses = (className: string): void => {
    for (const candidate of className.split(' ')) {
      if (candidate !== '') {
        classes.add(candidate)
      }
    }
  }
  for (const { props } of buildMatrix()) {
    for (const variant of renderedPropVariants(props)) {
      addClasses(touchableAreaCompatClassName(variant))
    }
    const group = groupContainerName(props)
    if (group !== undefined) {
      // $group-* pairs render inside a FlexCompat group container on the board.
      addClasses(flexCompatClassName({ group, fill: true }))
    }
  }
  return [...classes].sort()
}

/** The exact `touchable-parity.classes.txt` file contents. */
export function touchableAreaParityManifestFileContents(): string {
  const lines = [
    '# Generated by `bun run generate:option-classes` — do not edit.',
    '# What this is: the Tailwind `@source` manifest for the TouchableArea (Spore) parity page.',
    '# TouchableAreaCompat computes its className at runtime from props, so the Tailwind scanner',
    '# never sees these candidates in source files; this enumeration (every parity-matrix case the',
    '# verification board renders, produced through the real compiler) is how their CSS gets emitted.',
    '# Guarded by packages/tailwind/src/parity/touchable-area/class-manifest.test.ts (regenerate-and-diff).',
    ...buildTouchableAreaParityClassManifest(),
  ]
  return `${lines.join('\n')}\n`
}
