export enum Screens {
  Accounts = 'Accounts',
  AccountStack = 'AccountStack',
  Balances = 'Balances',
  Camera = 'Camera',
  CurrencySelector = 'CurrencySelector',
  Dev = 'Dev',
  Education = 'Education',
  Explore = 'Explore',
  ImportAccount = 'ImportAccount',
  Ledger = 'Ledger',
  Notifications = 'Notifications',
  NFTCollection = 'NFTCollection',
  OnboardingStack = 'OnboardingStack',
  RecipientSelector = 'RecipientSelector',
  SeedPhrase = 'SeedPhrase',
  Settings = 'Settings',
  SettingsChains = 'SettingsChains',
  SettingsStack = 'SettingsStack',
  SettingsSupport = 'SettingsSupport',
  SettingsTestConfigs = 'SettingsTestConfigs',
  Swap = 'Swap',
  SwapConfig = 'SwapConfig',
  TabNavigator = 'TabNavigator',
  TokenDetails = 'TokenDetails',
  Transfer = 'Transfer',
  Welcome = 'Welcome',
}

export enum OnboardingScreens {
  Backup = 'OnboardingBackup',
  BackupCloud = 'OnboardingBackupCloud',
  BackupManual = 'OnboardingBackupManual',
  NameAndColor = 'OnboardingCreateWallet',
  Landing = 'OnboardingLanding',
  Notifications = 'OnboardingNotifications',
  Outro = 'OnboardingOutro',
  Security = 'OnboardingSecurity',
}

export enum Tabs {
  Explore = 'ExploreTab',
  Home = 'HomeTab',
  NFT = 'NFTTab',
  Portfolio = 'PortfolioTab',
  Swap = 'SwapTab',
}
