export enum Screens {
  Accounts = 'Accounts',
  AccountStack = 'AccountStack',
  Camera = 'Camera',
  CurrencySelector = 'CurrencySelector',
  Dev = 'Dev',
  Education = 'Education',
  Explore = 'Explore',
  ExploreTokens = 'ExploreTokens',
  ExploreFavorites = 'ExploreFavorites',
  Home = 'Home',
  ImportAccount = 'ImportAccount',
  Ledger = 'Ledger',
  Notifications = 'Notifications',
  NFTCollection = 'NFTCollection',
  NFTItem = 'NFTItem',
  OnboardingStack = 'OnboardingStack',
  PortfolioTokens = 'PortfolioTokens',
  PortfolioNFTs = 'PortfolioNFTs',
  ProfileStack = 'ProfileStack',
  RecipientSelector = 'RecipientSelector',
  SeedPhrase = 'SeedPhrase',
  Settings = 'Settings',
  SettingsWallet = 'SettingsWallet',
  SettingsWalletEdit = 'SettingsWalletEdit',
  SettingsWalletManageConnection = 'SettingsWalletManageConnection',
  SettingsHelpCenter = 'SettingsHelpCenter',
  SettingsChains = 'SettingsChains',
  SettingsStack = 'SettingsStack',
  SettingsSupport = 'SettingsSupport',
  SettingsTestConfigs = 'SettingsTestConfigs',
  Swap = 'Swap',
  SwapConfig = 'SwapConfig',
  TabNavigator = 'TabNavigator',
  TokenDetails = 'TokenDetails',
  Transfer = 'Transfer',
  User = 'User',
  WebView = 'WebView',
  Welcome = 'Welcome',
}

export enum OnboardingScreens {
  Backup = 'OnboardingBackup',
  BackupCloud = 'OnboardingBackupCloud',
  BackupCloudProcessing = 'OnboardingBackupCloudProcessing',
  BackupManual = 'OnboardingBackupManual',
  Landing = 'OnboardingLanding',
  EditName = 'EditName',
  SelectColor = 'SelectColor',
  Notifications = 'OnboardingNotifications',
  Outro = 'OnboardingOutro',
  Security = 'OnboardingSecurity',

  // import
  ImportMethod = 'ImportMethod',
  SeedPhraseInput = 'SeedPhraseInput',
  PrivateKeyInput = 'PrivateKeyInput',
  RestoreWallet = 'RestoreWallet',
  SelectWallet = 'SelectWallet',
  WatchWallet = 'WatchWallet',
}

export enum Tabs {
  Explore = 'ExploreTab',
  Home = 'HomeTab',
  Profile = 'Profile',
}
