/// <reference lib="webworker" />
/* eslint-disable no-restricted-globals */

import 'workbox-precaching' // defines __WB_MANIFEST

import { clientsClaim } from 'workbox-core'
import { precacheAndRoute } from 'workbox-precaching'
import { registerRoute } from 'workbox-routing'

import { DocumentRoute } from './document'
import { filterPrecacheEntries } from './precache'

declare const self: ServiceWorkerGlobalScope

clientsClaim()
self.skipWaiting()

// Registers a handler for the document route for cached assets.
// This must be done before setting up workbox-precaching, so that it takes precedence.
registerRoute(new DocumentRoute())

// Precaches and routes for the assets generated by the build process.
const assets = self.__WB_MANIFEST.filter(filterPrecacheEntries)
precacheAndRoute(assets)

// TODO(zzmp): Write a cypress test to guarantee that it is loading
