blank_issues_enabled: true
contact_links:
  - name: Support
    url: https://discord.com/invite/kinetixfi
    about: Please ask and answer questions here
  - name: List a token
    url: https://github.com/Uniswap/default-token-list#adding-a-token
    about: Any requests to add a token to Uniswap should go here
