export const fontFamily = {
  serif: 'serif',
  sansSerif: {
    regular: 'Inter-Regular',
    medium: 'Inter-Medium',
    semibold: 'Inter-SemiBold',
    bold: 'Inter-Bold',
    monospace: 'InputMono-Regular',
  },
}

export const textVariants = {
  headlineLarge: {
    fontFamily: fontFamily.sansSerif.semibold,
    fontSize: 40,
    lineHeight: 48,
    color: 'textPrimary',
    maxFontSizeMultiplier: 1.2,
  },
  headlineMedium: {
    fontFamily: fontFamily.sansSerif.medium,
    fontSize: 32,
    lineHeight: 38,
    color: 'textPrimary',
    maxFontSizeMultiplier: 1.2,
  },
  headlineSmall: {
    fontFamily: fontFamily.sansSerif.medium,
    fontSize: 24,
    lineHeight: 28,
    color: 'textPrimary',
    maxFontSizeMultiplier: 1.2,
  },
  subheadLarge: {
    fontFamily: fontFamily.sansSerif.medium,
    fontSize: 20,
    lineHeight: 24,
    color: 'textPrimary',
    maxFontSizeMultiplier: 1.4,
  },
  subheadSmall: {
    fontFamily: fontFamily.sansSerif.medium,
    fontSize: 14,
    lineHeight: 20,
    color: 'textPrimary',
    maxFontSizeMultiplier: 1.4,
  },
  bodyLarge: {
    fontFamily: fontFamily.sansSerif.medium,
    fontSize: 16,
    lineHeight: 24,
    color: 'textPrimary',
    maxFontSizeMultiplier: 1.4,
  },
  bodySmall: {
    fontFamily: fontFamily.sansSerif.regular,
    fontSize: 14,
    lineHeight: 20,
    color: 'textPrimary',
    maxFontSizeMultiplier: 1.4,
  },
  bodyMicro: {
    fontFamily: fontFamily.sansSerif.regular,
    fontSize: 12,
    lineHeight: 16,
    color: 'textPrimary',
    maxFontSizeMultiplier: 1.4,
  },
  buttonLabelLarge: {
    fontFamily: fontFamily.sansSerif.semibold,
    fontSize: 20,
    lineHeight: 24,
    color: 'textPrimary',
    maxFontSizeMultiplier: 1.2,
  },
  buttonLabelMedium: {
    fontFamily: fontFamily.sansSerif.semibold,
    fontSize: 16,
    lineHeight: 20,
    color: 'textPrimary',
    maxFontSizeMultiplier: 1.2,
  },
  buttonLabelSmall: {
    fontFamily: fontFamily.sansSerif.semibold,
    fontSize: 14,
    lineHeight: 20,
    color: 'textPrimary',
    maxFontSizeMultiplier: 1.2,
  },
  buttonLabelMicro: {
    fontFamily: fontFamily.sansSerif.semibold,
    fontSize: 12,
    lineHeight: 16,
    color: 'textPrimary',
    maxFontSizeMultiplier: 1.2,
  },
  monospace: {
    fontFamily: fontFamily.sansSerif.monospace,
    fontSize: 14,
    lineHeight: 20,
    color: 'textPrimary',
    maxFontSizeMultiplier: 1.2,
  },
}
