// Follow up to remove: WEB-5827
// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts"
// @generated from file conversionproxy/v1/api.proto (package conversionproxy.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ProxyRequest, ProxyResponse } from "./api_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service conversionproxy.v1.ConversionProxyService
 */
export const ConversionProxyService = {
  typeName: "conversionproxy.v1.ConversionProxyService",
  methods: {
    /**
     * @generated from rpc conversionproxy.v1.ConversionProxyService.Proxy
     */
    proxy: {
      name: "Proxy",
      I: ProxyRequest,
      O: ProxyResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

