import { Contract } from '@ethersproject/contracts';
import { ArgentWalletDetector, EnsPublicResolver, EnsRegistrar, Erc20, Erc721, Erc1155, Weth } from 'abis/types';
import { NonfungiblePositionManager, Quoter, TickLens, UniswapInterfaceMulticall } from 'types/v3';
import { V3Migrator } from 'types/v3/V3Migrator';
export declare function useContract<T extends Contract = Contract>(addressOrAddressMap: string | {
    [chainId: number]: string;
} | undefined, ABI: any, withSignerIfPossible?: boolean): T | null;
export declare function useV2MigratorContract(): V3Migrator | null;
export declare function useTokenContract(tokenAddress?: string, withSignerIfPossible?: boolean): Erc20 | null;
export declare function useWETHContract(withSignerIfPossible?: boolean): Weth | null;
export declare function useERC721Contract(nftAddress?: string): Erc721 | null;
export declare function useERC1155Contract(nftAddress?: string): Erc1155 | null;
export declare function useArgentWalletDetectorContract(): ArgentWalletDetector | null;
export declare function useENSRegistrarContract(withSignerIfPossible?: boolean): EnsRegistrar | null;
export declare function useENSResolverContract(address: string | undefined, withSignerIfPossible?: boolean): EnsPublicResolver | null;
export declare function useBytes32TokenContract(tokenAddress?: string, withSignerIfPossible?: boolean): Contract | null;
export declare function useEIP2612Contract(tokenAddress?: string): Contract | null;
export declare function usePairContract(pairAddress?: string, withSignerIfPossible?: boolean): Contract | null;
export declare function useV2RouterContract(): Contract | null;
export declare function useInterfaceMulticall(): UniswapInterfaceMulticall;
export declare function useMerkleDistributorContract(): Contract | null;
export declare function useGovernanceV0Contract(): Contract | null;
export declare function useGovernanceV1Contract(): Contract | null;
export declare function useGovernanceBravoContract(): Contract | null;
export declare const useLatestGovernanceContract: typeof useGovernanceBravoContract;
export declare function useUniContract(): Contract | null;
export declare function useStakingContract(stakingAddress?: string, withSignerIfPossible?: boolean): Contract | null;
export declare function useV3NFTPositionManagerContract(withSignerIfPossible?: boolean): NonfungiblePositionManager | null;
export declare function useV3Quoter(): Quoter | null;
export declare function useTickLens(): TickLens | null;
