/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { StakingImpl, StakingImplInterface } from "../StakingImpl";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "grgVault",
        type: "address",
      },
      {
        internalType: "address",
        name: "poolRegistry",
        type: "address",
      },
      {
        internalType: "address",
        name: "rigoToken",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "target",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "caller",
        type: "address",
      },
    ],
    name: "AuthorizedAddressAdded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "target",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "caller",
        type: "address",
      },
    ],
    name: "AuthorizedAddressRemoved",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "string",
        name: "reason",
        type: "string",
      },
    ],
    name: "CatchStringEvent",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "epoch",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "numPoolsToFinalize",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "rewardsAvailable",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "totalFeesCollected",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "totalWeightedStake",
        type: "uint256",
      },
    ],
    name: "EpochEnded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "epoch",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "rewardsPaid",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "rewardsRemaining",
        type: "uint256",
      },
    ],
    name: "EpochFinalized",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "grgAmount",
        type: "uint256",
      },
    ],
    name: "GrgMintEvent",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "staker",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "fromStatus",
        type: "uint8",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "fromPool",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "toStatus",
        type: "uint8",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "toPool",
        type: "bytes32",
      },
    ],
    name: "MoveStake",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "poolId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "oldOperatorShare",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "newOperatorShare",
        type: "uint32",
      },
    ],
    name: "OperatorShareDecreased",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "epochDurationInSeconds",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "rewardDelegatedStakeWeight",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "minimumPoolStake",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "cobbDouglasAlphaNumerator",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "cobbDouglasAlphaDenominator",
        type: "uint256",
      },
    ],
    name: "ParamsSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "exchangeAddress",
        type: "address",
      },
    ],
    name: "PopAdded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "exchangeAddress",
        type: "address",
      },
    ],
    name: "PopRemoved",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "rbPoolAddress",
        type: "address",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "poolId",
        type: "bytes32",
      },
    ],
    name: "RbPoolStakingPoolSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "bytes",
        name: "reason",
        type: "bytes",
      },
    ],
    name: "ReturnDataEvent",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "epoch",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "poolId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "operatorReward",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "membersReward",
        type: "uint256",
      },
    ],
    name: "RewardsPaid",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "staker",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "Stake",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "bytes32",
        name: "poolId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "address",
        name: "operator",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "operatorShare",
        type: "uint32",
      },
    ],
    name: "StakingPoolCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "epoch",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "poolId",
        type: "bytes32",
      },
    ],
    name: "StakingPoolEarnedRewardsInEpoch",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "staker",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "Unstake",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "target",
        type: "address",
      },
    ],
    name: "addAuthorizedAddress",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "addr",
        type: "address",
      },
    ],
    name: "addPopAddress",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "aggregatedStatsByEpoch",
    outputs: [
      {
        internalType: "uint256",
        name: "rewardsAvailable",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "numPoolsToFinalize",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "totalFeesCollected",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "totalWeightedStake",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "totalRewardsFinalized",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "authorities",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "authorized",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "cobbDouglasAlphaDenominator",
    outputs: [
      {
        internalType: "uint32",
        name: "",
        type: "uint32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "cobbDouglasAlphaNumerator",
    outputs: [
      {
        internalType: "uint32",
        name: "",
        type: "uint32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "poolId",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "member",
        type: "address",
      },
    ],
    name: "computeRewardBalanceOfDelegator",
    outputs: [
      {
        internalType: "uint256",
        name: "reward",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "poolId",
        type: "bytes32",
      },
    ],
    name: "computeRewardBalanceOfOperator",
    outputs: [
      {
        internalType: "uint256",
        name: "reward",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "rigoblockPoolAddress",
        type: "address",
      },
    ],
    name: "createStakingPool",
    outputs: [
      {
        internalType: "bytes32",
        name: "poolId",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "poolAccount",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "popReward",
        type: "uint256",
      },
    ],
    name: "creditPopReward",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "currentEpoch",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "currentEpochStartTimeInSeconds",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "poolId",
        type: "bytes32",
      },
      {
        internalType: "uint32",
        name: "newOperatorShare",
        type: "uint32",
      },
    ],
    name: "decreaseStakingPoolOperatorShare",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "endEpoch",
    outputs: [
      {
        internalType: "uint256",
        name: "numPoolsToFinalize",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "epochDurationInSeconds",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "poolId",
        type: "bytes32",
      },
    ],
    name: "finalizePool",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getAuthorizedAddresses",
    outputs: [
      {
        internalType: "address[]",
        name: "",
        type: "address[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getCurrentEpochEarliestEndTimeInSeconds",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "enum IStructs.StakeStatus",
        name: "stakeStatus",
        type: "uint8",
      },
    ],
    name: "getGlobalStakeByStatus",
    outputs: [
      {
        components: [
          {
            internalType: "uint64",
            name: "currentEpoch",
            type: "uint64",
          },
          {
            internalType: "uint96",
            name: "currentEpochBalance",
            type: "uint96",
          },
          {
            internalType: "uint96",
            name: "nextEpochBalance",
            type: "uint96",
          },
        ],
        internalType: "struct IStructs.StoredBalance",
        name: "balance",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getGrgContract",
    outputs: [
      {
        internalType: "contract IRigoToken",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getGrgVault",
    outputs: [
      {
        internalType: "contract IGrgVault",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "staker",
        type: "address",
      },
      {
        internalType: "enum IStructs.StakeStatus",
        name: "stakeStatus",
        type: "uint8",
      },
    ],
    name: "getOwnerStakeByStatus",
    outputs: [
      {
        components: [
          {
            internalType: "uint64",
            name: "currentEpoch",
            type: "uint64",
          },
          {
            internalType: "uint96",
            name: "currentEpochBalance",
            type: "uint96",
          },
          {
            internalType: "uint96",
            name: "nextEpochBalance",
            type: "uint96",
          },
        ],
        internalType: "struct IStructs.StoredBalance",
        name: "balance",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getParams",
    outputs: [
      {
        internalType: "uint256",
        name: "_epochDurationInSeconds",
        type: "uint256",
      },
      {
        internalType: "uint32",
        name: "_rewardDelegatedStakeWeight",
        type: "uint32",
      },
      {
        internalType: "uint256",
        name: "_minimumPoolStake",
        type: "uint256",
      },
      {
        internalType: "uint32",
        name: "_cobbDouglasAlphaNumerator",
        type: "uint32",
      },
      {
        internalType: "uint32",
        name: "_cobbDouglasAlphaDenominator",
        type: "uint32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getPoolRegistry",
    outputs: [
      {
        internalType: "contract IPoolRegistry",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "staker",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "poolId",
        type: "bytes32",
      },
    ],
    name: "getStakeDelegatedToPoolByOwner",
    outputs: [
      {
        components: [
          {
            internalType: "uint64",
            name: "currentEpoch",
            type: "uint64",
          },
          {
            internalType: "uint96",
            name: "currentEpochBalance",
            type: "uint96",
          },
          {
            internalType: "uint96",
            name: "nextEpochBalance",
            type: "uint96",
          },
        ],
        internalType: "struct IStructs.StoredBalance",
        name: "balance",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "poolId",
        type: "bytes32",
      },
    ],
    name: "getStakingPool",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "operator",
            type: "address",
          },
          {
            internalType: "address",
            name: "stakingPal",
            type: "address",
          },
          {
            internalType: "uint32",
            name: "operatorShare",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "stakingPalShare",
            type: "uint32",
          },
        ],
        internalType: "struct IStructs.Pool",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "poolId",
        type: "bytes32",
      },
    ],
    name: "getStakingPoolStatsThisEpoch",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "feesCollected",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "weightedStake",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "membersStake",
            type: "uint256",
          },
        ],
        internalType: "struct IStructs.PoolStats",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "staker",
        type: "address",
      },
    ],
    name: "getTotalStake",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "poolId",
        type: "bytes32",
      },
    ],
    name: "getTotalStakeDelegatedToPool",
    outputs: [
      {
        components: [
          {
            internalType: "uint64",
            name: "currentEpoch",
            type: "uint64",
          },
          {
            internalType: "uint96",
            name: "currentEpochBalance",
            type: "uint96",
          },
          {
            internalType: "uint96",
            name: "nextEpochBalance",
            type: "uint96",
          },
        ],
        internalType: "struct IStructs.StoredBalance",
        name: "balance",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "grgReservedForPoolRewards",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "init",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "minimumPoolStake",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "enum IStructs.StakeStatus",
            name: "status",
            type: "uint8",
          },
          {
            internalType: "bytes32",
            name: "poolId",
            type: "bytes32",
          },
        ],
        internalType: "struct IStructs.StakeInfo",
        name: "from",
        type: "tuple",
      },
      {
        components: [
          {
            internalType: "enum IStructs.StakeStatus",
            name: "status",
            type: "uint8",
          },
          {
            internalType: "bytes32",
            name: "poolId",
            type: "bytes32",
          },
        ],
        internalType: "struct IStructs.StakeInfo",
        name: "to",
        type: "tuple",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "moveStake",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "poolIdByRbPoolAccount",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "poolStatsByEpoch",
    outputs: [
      {
        internalType: "uint256",
        name: "feesCollected",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "weightedStake",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "membersStake",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "target",
        type: "address",
      },
    ],
    name: "removeAuthorizedAddress",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "target",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "index",
        type: "uint256",
      },
    ],
    name: "removeAuthorizedAddressAtIndex",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "addr",
        type: "address",
      },
    ],
    name: "removePopAddress",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "rewardDelegatedStakeWeight",
    outputs: [
      {
        internalType: "uint32",
        name: "",
        type: "uint32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    name: "rewardsByPoolId",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_epochDurationInSeconds",
        type: "uint256",
      },
      {
        internalType: "uint32",
        name: "_rewardDelegatedStakeWeight",
        type: "uint32",
      },
      {
        internalType: "uint256",
        name: "_minimumPoolStake",
        type: "uint256",
      },
      {
        internalType: "uint32",
        name: "_cobbDouglasAlphaNumerator",
        type: "uint32",
      },
      {
        internalType: "uint32",
        name: "_cobbDouglasAlphaDenominator",
        type: "uint32",
      },
    ],
    name: "setParams",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "poolId",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "newStakingPalAddress",
        type: "address",
      },
    ],
    name: "setStakingPalAddress",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "stake",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "stakingContract",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "unstake",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "validPops",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "poolId",
        type: "bytes32",
      },
    ],
    name: "withdrawDelegatorRewards",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class StakingImpl__factory {
  static readonly abi = _abi;
  static createInterface(): StakingImplInterface {
    return new utils.Interface(_abi) as StakingImplInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): StakingImpl {
    return new Contract(address, _abi, signerOrProvider) as StakingImpl;
  }
}
