#!/usr/bin/env bun
/**
 * Generates config/oxlint-plugins/tamagui-baseline.json — the grandfathered
 * allowlist for `universe-custom/no-tamagui-styling` (INFRA-2958).
 *
 * It runs oxlint with ONLY that rule enabled (baseline disabled via
 * TAMAGUI_BASELINE=off) over the CI lint surface (apps/ + packages/), then
 * folds the diagnostics into per-file counts per category. Using the rule
 * itself as the scanner guarantees the baseline and the rule can never
 * disagree about what counts as a violation.
 *
 * Usage:
 *   bun scripts/tamagui-migration/generate-tamagui-baseline.ts           # rewrite the baseline
 *   bun scripts/tamagui-migration/generate-tamagui-baseline.ts --check   # CI drift guard: fail if stale
 */
import { readFileSync, rmSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { rootIgnorePatterns } from '../../oxlint.config'

const REPO_ROOT = join(import.meta.dir, '../..')
const BASELINE_PATH = join(REPO_ROOT, 'config/oxlint-plugins/tamagui-baseline.json')
// Matches the CI lint surface: labs/ is .nxignore'd (never linted in CI) and
// the rule is off there; config/ and scripts/ are in rootIgnorePatterns.
const SCAN_ROOTS = ['apps', 'packages']
const TEMP_CONFIG_PATH = join(REPO_ROOT, '.tamagui-baseline.oxlintrc.tmp.json')

export type TamaguiCategory = 'styled' | 'animation' | 'group'

export interface TamaguiDiagnostic {
  filename: string
  message: string
}

export type TamaguiBaselineFiles = Record<string, Partial<Record<TamaguiCategory, number>>>

export function classifyMessage(message: string): TamaguiCategory | undefined {
  if (message.includes('styled() calls are banned')) {
    return 'styled'
  }
  if (message.includes('animation preset prop')) {
    return 'animation'
  }
  if (message.includes('$group-* prop')) {
    return 'group'
  }
  return undefined
}

export function toRepoRelativePath(filename: string, repoRoot: string): string {
  const normalized = filename.split('\\').join('/')
  const rootPrefix = `${repoRoot.split('\\').join('/')}/`
  return normalized.startsWith(rootPrefix) ? normalized.slice(rootPrefix.length) : normalized
}

// Exempt prefixes → oxlint ignore globs. Trailing-slash normalization keeps
// directory-boundary semantics (`scripts/tamagui-census` must not ignore
// `scripts/tamagui-census-foo/`), and `**` makes the ignore recursive to
// match the startsWith semantics of the rule and Danger legs.
export function toExemptIgnorePatterns(pathPrefixes: string[]): string[] {
  return pathPrefixes.map((prefix) => `${prefix.endsWith('/') ? prefix : `${prefix}/`}**`)
}

export function buildBaselineFiles(diagnostics: TamaguiDiagnostic[], repoRoot: string): TamaguiBaselineFiles {
  const files: TamaguiBaselineFiles = {}
  for (const diagnostic of diagnostics) {
    const category = classifyMessage(diagnostic.message)
    if (!category) {
      continue
    }
    const relPath = toRepoRelativePath(diagnostic.filename, repoRoot)
    const entry = (files[relPath] ??= {})
    entry[category] = (entry[category] ?? 0) + 1
  }
  return Object.fromEntries(Object.entries(files).sort(([a], [b]) => (a < b ? -1 : 1)))
}

export function renderBaseline(files: TamaguiBaselineFiles): string {
  const totals = { styled: 0, animation: 0, group: 0, files: Object.keys(files).length }
  for (const entry of Object.values(files)) {
    totals.styled += entry.styled ?? 0
    totals.animation += entry.animation ?? 0
    totals.group += entry.group ?? 0
  }
  const baseline = {
    '//': 'GENERATED by `bun scripts/tamagui-migration/generate-tamagui-baseline.ts` — do not edit by hand. Grandfathered Tamagui styling sites for universe-custom/no-tamagui-styling (per-file counts; the rule fires only beyond these).',
    totals,
    files,
  }
  return `${JSON.stringify(baseline, null, 2)}\n`
}

function runScan(): TamaguiDiagnostic[] {
  // Migration tooling paths are exempt from the gate (shared list, also
  // consumed by the oxlint rule and dangerfile) — keep them out of the
  // baseline so fixture churn never rewrites it.
  const { pathPrefixes } = JSON.parse(
    readFileSync(join(REPO_ROOT, 'config/oxlint-plugins/tamagui-migration-exempt-paths.json'), 'utf8'),
  ) as { pathPrefixes: string[] }
  const scanConfig = {
    plugins: [],
    categories: { correctness: 'off' },
    jsPlugins: [join(REPO_ROOT, 'config/oxlint-plugins/universe-custom.js')],
    rules: { 'universe-custom/no-tamagui-styling': 'warn' },
    ignorePatterns: [...rootIgnorePatterns, 'labs/**', ...toExemptIgnorePatterns(pathPrefixes)],
  }
  writeFileSync(TEMP_CONFIG_PATH, JSON.stringify(scanConfig, null, 2))
  try {
    const result = Bun.spawnSync(
      [join(REPO_ROOT, 'node_modules/.bin/oxlint'), '-c', TEMP_CONFIG_PATH, '--format', 'json', ...SCAN_ROOTS],
      {
        cwd: REPO_ROOT,
        env: { ...process.env, TAMAGUI_BASELINE: 'off' },
        stdout: 'pipe',
        stderr: 'pipe',
      },
    )
    const stdout = result.stdout.toString()
    if (result.exitCode !== 0) {
      throw new Error(`oxlint scan failed (exit ${result.exitCode}): ${result.stderr.toString().slice(0, 2000)}`)
    }
    const parsed = JSON.parse(stdout) as { diagnostics?: TamaguiDiagnostic[] }
    return (parsed.diagnostics ?? []).filter((d) => classifyMessage(d.message))
  } finally {
    rmSync(TEMP_CONFIG_PATH, { force: true })
  }
}

function main(): void {
  const isCheck = process.argv.includes('--check')
  const rendered = renderBaseline(buildBaselineFiles(runScan(), REPO_ROOT))

  if (isCheck) {
    let existing = ''
    try {
      existing = readFileSync(BASELINE_PATH, 'utf8')
    } catch {
      // missing baseline is stale by definition
    }
    if (existing !== rendered) {
      console.error(
        'tamagui-baseline.json is stale. Run `bun scripts/tamagui-migration/generate-tamagui-baseline.ts` and commit the result.',
      )
      process.exit(1)
    }
    console.log('tamagui-baseline.json is up to date.')
    return
  }

  writeFileSync(BASELINE_PATH, rendered)
  const { totals } = JSON.parse(rendered) as { totals: Record<string, number> }
  console.log(
    `Wrote ${BASELINE_PATH}: ${totals.styled} styled(), ${totals.animation} animation-preset, ${totals.group} $group-* sites across ${totals.files} files.`,
  )
}

if (import.meta.main) {
  main()
}
