// Chart Dimension Constants
export const CHART_DIMENSIONS = {
  // Chart dimensions
  LIQUIDITY_CHART_HEIGHT: 200,
  LIQUIDITY_CHART_WIDTH: 120,
  LIQUIDITY_SECTION_OFFSET: 16,
  LIQUIDITY_BARS_SPACING: 10,
  LIQUIDITY_BAR_HEIGHT: 3,
  LIQUIDITY_BAR_SPACING: 1,
  SOLID_MIN_MAX_LINE_HEIGHT: 3,
} as const
