source "https://rubygems.org"

gem 'fastlane', '2.215.0'
# Exclude problematic versions of cocoapods and activesupport that causes build failures.
gem 'cocoapods', '1.15.0'
gem 'activesupport', '7.1.2'
gem 'xcodeproj', '1.27.0'
gem 'concurrent-ruby', '1.3.4'

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
