source "https://rubygems.org"

gem 'fastlane', '2.228.0'
gem 'cocoapods', '1.16.2'
gem 'activesupport', '7.1.2'
gem 'xcodeproj', '1.27.0'
gem 'concurrent-ruby', '1.3.4'

# Ruby 3.4.0 removed these from the standard library.
# See: https://github.com/fastlane/fastlane/issues/29183
# See: https://www.ruby-lang.org/en/news/2024/12/25/ruby-3-4-0-released/
gem 'abbrev'
gem 'base64'
gem 'bigdecimal'
gem 'benchmark'
gem 'drb'
gem 'logger'
gem 'mutex_m'
gem 'nkf'
gem 'ostruct'

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
