# changes from here: https://docs.expo.dev/bare/installing-expo-modules/
require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'

$FirebaseSDKVersion = '8.8.0'
$RNFirebaseAnalyticsWithoutAdIdSupport=true

target 'Uniswap' do
  use_expo_modules!(exclude: ['expo-constants','expo-file-system', 'expo-image-loader', 'expo-font', 'expo-keep-awake', 'expo-error-recovery'])
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'UniswapTests' do
    inherit! :complete
    # Pods for testing
  end

  pod 'EthersRS', :path =>  '../node_modules/@cmcewen/ethers-rs-mobile'

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # Pinning fix for command line build
  # https://github.com/facebook/react-native/issues/31480#issuecomment-915583038
  
  if ENV['USE_FLIPPER']
    use_flipper!({'Flipper-Folly' => '2.6.9'})
    pod 'react-native-flipper', :path =>  '../node_modules/react-native-flipper'
  end

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < '9.0'.to_f
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
        end

        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      end
     end
  end
end