version: '3'
services:
  graph-node:
    image: graphprotocol/graph-node
    ports:
      - '3000:8000'
      - '8001:8001'
      - '8020:8020'
      - '8030:8030'
      - '8040:8040'
    depends_on:
      - ipfs
      - postgres
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      postgres_host: postgres
      postgres_user: graph-node
      postgres_pass: let-me-in
      postgres_db: graph-node
      ipfs: 'ipfs:5001'
      ethereum: 'smartbch:https://smartbch.fountainhead.cash/mainnet'
      GRAPH_LOG: info
  ipfs:
    image: 'ipfs/kubo:v0.17.0'
    ports:
      - '5001:5001'
    volumes:
      - './data/ipfs:/data/ipfs:Z'
  postgres:
    image: postgres
    expose:
      - '5432'
    command:
      - postgres
      - '-cshared_preload_libraries=pg_stat_statements'
      - '-cmax_connections=200'
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph-node
      PGDATA: /var/lib/postgresql/data
      POSTGRES_INITDB_ARGS: '-E UTF8 --locale=C'
    volumes:
      - './data/postgres:/var/lib/postgresql/data:Z'
