import { fonts } from 'ui/src/theme/fonts'

const DEFAULT_FONT_COLOR = 'neutral1'

export const textVariants = {
  heading1: {
    fontFamily: fonts.heading1.family,
    fontSize: fonts.heading1.fontSize,
    lineHeight: fonts.heading1.lineHeight,
    fontWeight: fonts.heading1.fontWeight,
    color: DEFAULT_FONT_COLOR,
    maxFontSizeMultiplier: fonts.heading1.maxFontSizeMultiplier,
  },
  heading2: {
    fontFamily: fonts.heading2.family,
    fontSize: fonts.heading2.fontSize,
    lineHeight: fonts.heading2.lineHeight,
    fontWeight: fonts.heading2.fontWeight,
    color: DEFAULT_FONT_COLOR,
    maxFontSizeMultiplier: fonts.heading2.maxFontSizeMultiplier,
  },
  heading3: {
    fontFamily: fonts.heading3.family,
    fontSize: fonts.heading3.fontSize,
    lineHeight: fonts.heading3.lineHeight,
    fontWeight: fonts.heading3.fontWeight,
    color: DEFAULT_FONT_COLOR,
    maxFontSizeMultiplier: fonts.heading3.maxFontSizeMultiplier,
  },
  subheading1: {
    fontFamily: fonts.subheading1.family,
    fontSize: fonts.subheading1.fontSize,
    lineHeight: fonts.subheading1.lineHeight,
    fontWeight: fonts.subheading1.fontWeight,
    color: DEFAULT_FONT_COLOR,
    maxFontSizeMultiplier: fonts.subheading1.maxFontSizeMultiplier,
  },
  subheading2: {
    fontFamily: fonts.subheading2.family,
    fontSize: fonts.subheading2.fontSize,
    lineHeight: fonts.subheading2.lineHeight,
    fontWeight: fonts.subheading2.fontWeight,
    color: DEFAULT_FONT_COLOR,
    maxFontSizeMultiplier: fonts.subheading2.maxFontSizeMultiplier,
  },
  body1: {
    fontFamily: fonts.body1.family,
    fontSize: fonts.body1.fontSize,
    lineHeight: fonts.body1.lineHeight,
    fontWeight: fonts.body1.fontWeight,
    color: DEFAULT_FONT_COLOR,
    maxFontSizeMultiplier: fonts.body1.maxFontSizeMultiplier,
  },
  body2: {
    fontFamily: fonts.body2.family,
    fontSize: fonts.body2.fontSize,
    lineHeight: fonts.body2.lineHeight,
    fontWeight: fonts.body2.fontWeight,
    color: DEFAULT_FONT_COLOR,
    maxFontSizeMultiplier: fonts.body2.maxFontSizeMultiplier,
  },
  body3: {
    fontFamily: fonts.body3.family,
    fontSize: fonts.body3.fontSize,
    lineHeight: fonts.body3.lineHeight,
    fontWeight: fonts.body3.fontWeight,
    color: DEFAULT_FONT_COLOR,
    maxFontSizeMultiplier: fonts.body3.maxFontSizeMultiplier,
  },
  buttonLabel1: {
    fontFamily: fonts.buttonLabel1.family,
    fontSize: fonts.buttonLabel1.fontSize,
    lineHeight: fonts.buttonLabel1.lineHeight,
    fontWeight: fonts.buttonLabel1.fontWeight,
    color: DEFAULT_FONT_COLOR,
    maxFontSizeMultiplier: fonts.buttonLabel1.maxFontSizeMultiplier,
  },
  buttonLabel2: {
    fontFamily: fonts.buttonLabel2.family,
    fontSize: fonts.buttonLabel2.fontSize,
    lineHeight: fonts.buttonLabel2.lineHeight,
    fontWeight: fonts.buttonLabel2.fontWeight,
    color: DEFAULT_FONT_COLOR,
    maxFontSizeMultiplier: fonts.buttonLabel2.maxFontSizeMultiplier,
  },
  buttonLabel3: {
    fontFamily: fonts.buttonLabel3.family,
    fontSize: fonts.buttonLabel3.fontSize,
    lineHeight: fonts.buttonLabel3.lineHeight,
    fontWeight: fonts.buttonLabel3.fontWeight,
    color: DEFAULT_FONT_COLOR,
    maxFontSizeMultiplier: fonts.buttonLabel3.maxFontSizeMultiplier,
  },
  buttonLabel4: {
    fontFamily: fonts.buttonLabel4.family,
    fontSize: fonts.buttonLabel4.fontSize,
    lineHeight: fonts.buttonLabel4.lineHeight,
    fontWeight: fonts.buttonLabel4.fontWeight,
    color: DEFAULT_FONT_COLOR,
    maxFontSizeMultiplier: fonts.buttonLabel4.maxFontSizeMultiplier,
  },
  monospace: {
    fontFamily: fonts.monospace.family,
    fontSize: fonts.monospace.fontSize,
    lineHeight: fonts.monospace.lineHeight,
    color: DEFAULT_FONT_COLOR,
    maxFontSizeMultiplier: fonts.monospace.maxFontSizeMultiplier,
  },
}
