import { fonts } from 'ui/src/theme/fonts'

const DEFAULT_FONT_COLOR = 'neutral1'

export const textVariants = {
  headlineLarge: {
    fontFamily: fonts.headlineLarge.family,
    fontSize: fonts.headlineLarge.fontSize,
    lineHeight: fonts.headlineLarge.lineHeight,
    fontWeight: fonts.headlineLarge.fontWeight,
    color: DEFAULT_FONT_COLOR,
    maxFontSizeMultiplier: fonts.headlineLarge.maxFontSizeMultiplier,
  },
  headlineMedium: {
    fontFamily: fonts.headlineMedium.family,
    fontSize: fonts.headlineMedium.fontSize,
    lineHeight: fonts.headlineMedium.lineHeight,
    fontWeight: fonts.headlineMedium.fontWeight,
    color: DEFAULT_FONT_COLOR,
    maxFontSizeMultiplier: fonts.headlineMedium.maxFontSizeMultiplier,
  },
  headlineSmall: {
    fontFamily: fonts.headlineSmall.family,
    fontSize: fonts.headlineSmall.fontSize,
    lineHeight: fonts.headlineSmall.lineHeight,
    fontWeight: fonts.headlineSmall.fontWeight,
    color: DEFAULT_FONT_COLOR,
    maxFontSizeMultiplier: fonts.headlineSmall.maxFontSizeMultiplier,
  },
  subheadLarge: {
    fontFamily: fonts.subheadLarge.family,
    fontSize: fonts.subheadLarge.fontSize,
    lineHeight: fonts.subheadLarge.lineHeight,
    fontWeight: fonts.subheadLarge.fontWeight,
    color: DEFAULT_FONT_COLOR,
    maxFontSizeMultiplier: fonts.subheadLarge.maxFontSizeMultiplier,
  },
  subheadSmall: {
    fontFamily: fonts.subheadSmall.family,
    fontSize: fonts.subheadSmall.fontSize,
    lineHeight: fonts.subheadSmall.lineHeight,
    fontWeight: fonts.subheadSmall.fontWeight,
    color: DEFAULT_FONT_COLOR,
    maxFontSizeMultiplier: fonts.subheadSmall.maxFontSizeMultiplier,
  },
  bodyLarge: {
    fontFamily: fonts.bodyLarge.family,
    fontSize: fonts.bodyLarge.fontSize,
    lineHeight: fonts.bodyLarge.lineHeight,
    fontWeight: fonts.bodyLarge.fontWeight,
    color: DEFAULT_FONT_COLOR,
    maxFontSizeMultiplier: fonts.bodyLarge.maxFontSizeMultiplier,
  },
  bodySmall: {
    fontFamily: fonts.bodySmall.family,
    fontSize: fonts.bodySmall.fontSize,
    lineHeight: fonts.bodySmall.lineHeight,
    fontWeight: fonts.bodySmall.fontWeight,
    color: DEFAULT_FONT_COLOR,
    maxFontSizeMultiplier: fonts.bodySmall.maxFontSizeMultiplier,
  },
  bodyMicro: {
    fontFamily: fonts.bodyMicro.family,
    fontSize: fonts.bodyMicro.fontSize,
    lineHeight: fonts.bodyMicro.lineHeight,
    fontWeight: fonts.bodyMicro.fontWeight,
    color: DEFAULT_FONT_COLOR,
    maxFontSizeMultiplier: fonts.bodyMicro.maxFontSizeMultiplier,
  },
  buttonLabelLarge: {
    fontFamily: fonts.buttonLabelLarge.family,
    fontSize: fonts.buttonLabelLarge.fontSize,
    lineHeight: fonts.buttonLabelLarge.lineHeight,
    fontWeight: fonts.buttonLabelLarge.fontWeight,
    color: DEFAULT_FONT_COLOR,
    maxFontSizeMultiplier: fonts.buttonLabelLarge.maxFontSizeMultiplier,
  },
  buttonLabelMedium: {
    fontFamily: fonts.buttonLabelMedium.family,
    fontSize: fonts.buttonLabelMedium.fontSize,
    lineHeight: fonts.buttonLabelMedium.lineHeight,
    fontWeight: fonts.buttonLabelMedium.fontWeight,
    color: DEFAULT_FONT_COLOR,
    maxFontSizeMultiplier: fonts.buttonLabelMedium.maxFontSizeMultiplier,
  },
  buttonLabelSmall: {
    fontFamily: fonts.buttonLabelSmall.family,
    fontSize: fonts.buttonLabelSmall.fontSize,
    lineHeight: fonts.buttonLabelSmall.lineHeight,
    fontWeight: fonts.buttonLabelSmall.fontWeight,
    color: DEFAULT_FONT_COLOR,
    maxFontSizeMultiplier: fonts.buttonLabelSmall.maxFontSizeMultiplier,
  },
  buttonLabelMicro: {
    fontFamily: fonts.buttonLabelMicro.family,
    fontSize: fonts.buttonLabelMicro.fontSize,
    lineHeight: fonts.buttonLabelMicro.lineHeight,
    fontWeight: fonts.buttonLabelMicro.fontWeight,
    color: DEFAULT_FONT_COLOR,
    maxFontSizeMultiplier: fonts.buttonLabelMicro.maxFontSizeMultiplier,
  },
  monospace: {
    fontFamily: fonts.monospace.family,
    fontSize: fonts.monospace.fontSize,
    lineHeight: fonts.monospace.lineHeight,
    color: DEFAULT_FONT_COLOR,
    maxFontSizeMultiplier: fonts.monospace.maxFontSizeMultiplier,
  },
}
