// oxlint-disable eslint-js/no-restricted-syntax -- Node-side Playwright code: process.env is the config surface here (no app getConfig())
/**
 * Anvil launch configuration for the e2e fork (Node-side Playwright code).
 *
 * Fork blocks are pinned per chain (checked-in defaults in `fork-blocks.json`,
 * runtime overrides via `ANVIL_FORK_BLOCK` / `ANVIL_FORK_BLOCK_BASE`) so tests see
 * deterministic chain state instead of rotting against the live tip, and so the CI
 * RPC cache (keyed on os+chain+block in .github/actions/playwright_matrix_test) hits
 * across runs. Re-pin periodically; keep the pin recent enough for the uni RPC
 * gateway's archival depth.
 *
 * Debug output (`--print-traces` + `RUST_LOG=debug`) is opt-in via `ANVIL_VERBOSE`
 * to keep CI logs and disk usage sane. scripts/start-anvil.sh (the local flow, verbose
 * by default) consumes this module via scripts/anvil-spawn-args.ts, so the argv here
 * is the single source of truth.
 */
import { existsSync } from 'fs'
import * as path from 'path'
import forkBlockDefaults from '~/playwright/anvil/fork-blocks.json'
import type { AnvilForkSource } from '~/playwright/anvil/unirpc-fork'
import { buildForkArgs } from '~/playwright/anvil/unirpc-fork'

interface PinnedForkBlock {
  envVar: string
  defaultBlock: number
}

/** Chains with a pinned fork block: checked-in default plus its override env var. */
const PINNED_FORK_BLOCKS: Partial<Record<number, PinnedForkBlock>> = {
  1: { envVar: 'ANVIL_FORK_BLOCK', defaultBlock: forkBlockDefaults.mainnet },
  8453: { envVar: 'ANVIL_FORK_BLOCK_BASE', defaultBlock: forkBlockDefaults.base },
}

interface ForkChainDefaults {
  /** Free unkeyed public RPC. The QuickNode endpoints formerly used here have their methods paused due to abuse. */
  defaultForkUrl: string
  forkUrlEnvVar: string
  defaultPort: number
}

/**
 * Per-chain fork-source defaults shared by the Playwright anvil manager and
 * scripts/anvil-spawn-args.ts (the start-anvil.sh entry), so the URLs and ports
 * cannot drift between the two flows.
 */
const FORK_CHAIN_DEFAULTS: Partial<Record<number, ForkChainDefaults>> = {
  1: { defaultForkUrl: 'https://ethereum-rpc.publicnode.com', forkUrlEnvVar: 'ANVIL_FORK_URL', defaultPort: 8545 },
  8453: { defaultForkUrl: 'https://base-rpc.publicnode.com', forkUrlEnvVar: 'ANVIL_FORK_URL_BASE', defaultPort: 8546 },
}

/**
 * Resolves the static (non-uni-RPC) fork URL and default port for a chain: the
 * env override when set, otherwise the checked-in PublicNode default. Throws for
 * chains without checked-in defaults — spawning anvil against a guessed URL would
 * fail in a far less obvious way.
 */
function resolveForkChainDefaults(ctx: { chainId: number; env?: NodeJS.ProcessEnv }): {
  forkUrl: string
  defaultPort: number
} {
  const defaults = FORK_CHAIN_DEFAULTS[ctx.chainId]
  if (!defaults) {
    throw new Error(
      `No anvil fork defaults for chainId ${ctx.chainId} (known: ${Object.keys(FORK_CHAIN_DEFAULTS).join(', ')})`,
    )
  }
  const override = (ctx.env ?? process.env)[defaults.forkUrlEnvVar]?.trim()
  return {
    forkUrl: override !== undefined && override !== '' ? override : defaults.defaultForkUrl,
    defaultPort: defaults.defaultPort,
  }
}

/**
 * Resolves the pinned fork block for a chain: the env override when set, otherwise
 * the checked-in default. Returns undefined for chains without a pin (anvil then
 * forks at the tip). Throws on a malformed override — a typo silently forking at
 * the wrong block would defeat the pin.
 */
function resolvePinnedForkBlock(ctx: { chainId: number; env?: NodeJS.ProcessEnv }): number | undefined {
  const pin = PINNED_FORK_BLOCKS[ctx.chainId]
  if (!pin) {
    return undefined
  }

  const override = (ctx.env ?? process.env)[pin.envVar]?.trim()
  if (override === undefined || override === '') {
    return pin.defaultBlock
  }
  if (!/^\d+$/.test(override)) {
    throw new Error(`${pin.envVar} must be a decimal block number, got "${override}"`)
  }
  return Number.parseInt(override, 10)
}

/** Chain names for the committed `--load-state` fixture filenames (state/<name>-<block>.json). */
const LOAD_STATE_CHAIN_NAMES: Partial<Record<number, string>> = {
  1: 'mainnet',
  8453: 'base',
}

/**
 * Resolves the committed `--load-state` fixture for a chain + pinned block:
 * `state/<chain>-<block>.json` next to this module (generated by
 * scripts/generate-anvil-state.ts, which pre-funds the test wallet at the pin).
 *
 * The block number is part of the filename ON PURPOSE: a fixture dumped at one pin is
 * meaningless at another, so re-pinning automatically stops matching the stale fixture
 * (returning undefined) instead of silently loading wrong-block state. Runtime funding
 * then simply does all the work again. `ANVIL_LOAD_STATE` overrides with an explicit
 * path; `ANVIL_LOAD_STATE=0` (or `none`) disables loading entirely.
 */
function defaultStateDir(): string | undefined {
  // Playwright (CJS transpile) and bun both define __dirname; vitest's ESM transform
  // doesn't — unit tests pass an explicit stateDir instead.
  return typeof __dirname === 'string' ? path.join(__dirname, 'state') : undefined
}

function resolveLoadStatePath(ctx: {
  chainId: number
  forkBlockNumber: number | undefined
  env?: NodeJS.ProcessEnv
  /** Directory holding the committed fixtures. Default: `state/` next to this module. */
  stateDir?: string
}): string | undefined {
  const override = (ctx.env ?? process.env).ANVIL_LOAD_STATE?.trim()
  if (override === '0' || override?.toLowerCase() === 'none') {
    return undefined
  }
  if (override !== undefined && override !== '') {
    return override
  }

  const chainName = LOAD_STATE_CHAIN_NAMES[ctx.chainId]
  const stateDir = ctx.stateDir ?? defaultStateDir()
  if (chainName === undefined || ctx.forkBlockNumber === undefined || stateDir === undefined) {
    return undefined
  }
  const candidate = path.join(stateDir, `${chainName}-${ctx.forkBlockNumber}.json`)
  return existsSync(candidate) ? candidate : undefined
}

/** Opt-in anvil debug output (`--print-traces` + `RUST_LOG=debug`). Default: quiet. */
function isAnvilVerbose(env: NodeJS.ProcessEnv = process.env): boolean {
  const value = env.ANVIL_VERBOSE?.toLowerCase()
  return value === '1' || value === 'true'
}

/**
 * Builds the full anvil argv for the e2e fork: fork source (URL + auth headers),
 * pinned fork block (omitted when undefined), network binding, and the fixed chain
 * flags. `--prune-history` caps memory on long runs; `--print-traces` only in
 * verbose mode. scripts/start-anvil.sh consumes this via scripts/anvil-spawn-args.ts.
 *
 * Deliberately NOT passed: `--disable-min-priority-fee`. It drops anvil's suggested
 * gas price to the raw base fee (~0.1 gwei at the pinned block) while the suggested
 * priority fee stays at the 1-gwei default, so any node-filled `eth_sendTransaction`
 * is rejected with -32003 "max priority fee per gas higher than max fee per gas".
 * Without the flag suggestions are self-consistent, and explicit zero-tip
 * transactions still land (verified against anvil 1.7.1 at the pinned fork).
 */
function buildAnvilSpawnArgs(ctx: {
  forkSource: AnvilForkSource
  forkBlockNumber: number | undefined
  /** Committed pre-funded state fixture (see resolveLoadStatePath). Omitted when undefined. */
  loadStatePath?: string | undefined
  port: number
  host: string
  verbose: boolean
}): string[] {
  return [
    ...buildForkArgs(ctx.forkSource),
    ...(ctx.forkBlockNumber === undefined ? [] : ['--fork-block-number', String(ctx.forkBlockNumber)]),
    ...(ctx.loadStatePath === undefined ? [] : ['--load-state', ctx.loadStatePath]),
    '--port',
    String(ctx.port),
    '--host',
    ctx.host,
    '--hardfork',
    'prague',
    '--no-rate-limit',
    '--disable-code-size-limit',
    '--prune-history',
    ...(ctx.verbose ? ['--print-traces'] : []),
  ]
}

/**
 * Builds the `anvil_reset` fork params that restore the node to its launch state:
 * the SAME upstream and the SAME pinned block. A bare reset re-forks at the live
 * tip, which silently un-pins the chain state and tip-chases the RPC cache.
 * Reset drops all snapshots, so callers must treat it as recovery, never as
 * routine per-test cleanup (see fixtures/anvil.ts).
 */
function buildResetForkParams(ctx: { forkUrl: string; forkBlockNumber: number | undefined }): {
  jsonRpcUrl: string
  blockNumber?: bigint
} {
  return {
    jsonRpcUrl: ctx.forkUrl,
    ...(ctx.forkBlockNumber === undefined ? {} : { blockNumber: BigInt(ctx.forkBlockNumber) }),
  }
}

export {
  buildAnvilSpawnArgs,
  buildResetForkParams,
  isAnvilVerbose,
  resolveForkChainDefaults,
  resolveLoadStatePath,
  resolvePinnedForkBlock,
}
