name: Report
description: Report test failures on `main` via Slack
inputs:
  name:
    description: The name of the failing test to report
    required: true
  SLACK_WEBHOOK_URL:
    description: The Slack webhook URL to use to report a test failure
    required: true

runs:
  using: composite
  steps:
    # - if: github.ref_name == 'main'
    - uses: slackapi/slack-github-action@007b2c3c751a190b6f0f040e47ed024deaa72844
      with:
        payload: |
          {
            "text": "${{ inputs.name }} failing on `${{ github.ref_name }}`",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*${{ inputs.name }} failing on `${{ github.ref_name }}`:* <https://github.com/${{ github.repository}}/actions/runs/${{ github.run_id }}/jobs/${{ GITHUB_RUN_ATTEMPT }}|view failing action>"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "_This is blocking pull requests and promotions - please prioritize fixing the build._"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "plain_text",
                  "text": "!oncall web"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
