import { INTERFACE_NAV_HEIGHT } from 'ui/src/theme/heights'

export const CONNECT_WALLET_BANNER_HEIGHT = 216
export const CONNECT_WALLET_FIXED_BOTTOM_SECTION_HEIGHT = 200
const NAV_BORDER_HEIGHT = 1
export const TOTAL_INTERFACE_NAV_HEIGHT = INTERFACE_NAV_HEIGHT + NAV_BORDER_HEIGHT
export const ACTIVITY_TABLE_ROW_HEIGHT = 68
export const TOKENS_TABLE_ROW_HEIGHT = 67
export const POOLS_TABLE_ROW_HEIGHT = 67
export const LIMITS_TABLE_ROW_HEIGHT = 67
