import { INTERFACE_NAV_HEIGHT } from 'ui/src/theme/heights'

export const CONNECT_WALLET_BANNER_HEIGHT = 216
export const CONNECT_WALLET_FIXED_BOTTOM_SECTION_HEIGHT = 200
const NAV_BORDER_HEIGHT = 1
export const TOTAL_INTERFACE_NAV_HEIGHT = INTERFACE_NAV_HEIGHT + NAV_BORDER_HEIGHT
export const PORTFOLIO_TABLE_ROW_HEIGHT = 64
