import {
  addAllowAnalyticsSwitch,
  addAppearanceSetting,
  addBehaviorHistory,
  addBiometricSettings,
  addCloudBackup,
  addCompletedUnitagsIntroBoolean,
  addEnsState,
  addExperimentsSlice,
  addExtensionOnboardingState,
  addFiatCurrencySettings,
  addHiddenNfts,
  addLanguageSettings,
  addLastBalancesReport,
  addLastBalancesReportValue,
  addModalsState,
  addPasswordLockout,
  addPushNotifications,
  addPushNotificationsEnabledToAccounts,
  addReplaceAccountOptions,
  addSearchHistory,
  addSkippedUnitagBoolean,
  addSwapProtectionSetting,
  addTimeImportedAndDerivationIndex,
  addTokensVisibility,
  addTweaksStartingState,
  addUniconV2IntroModalBoolean,
  addWalletConnectPendingSessionAndSettings,
  addWalletIsFunded,
  changeNativeTypeToSignerMnemonic,
  convertHiddenNftsToNftsData,
  correctFailedFiatOnRampTxIds,
  deleteChainsSlice,
  deleteOldOnRampTxData,
  deleteRTKQuerySlices,
  emptyMigration,
  filterToSupportedChains,
  flattenTokenVisibility,
  migrateAndRemoveCloudBackupSlice,
  migrateBiometricSettings,
  migrateDappRequestInfoTypes,
  migrateFiatPurchaseTransactionInfo,
  moveSettingStateToGlobal,
  removeCoingeckoApiAndTokenLists,
  removeDataApi,
  removeDemoAccount,
  removeEnsState,
  removeExperimentsSlice,
  removeFlashbotsEnabledFromWalletSlice,
  removeLocalTypeAccounts,
  removeNonZeroDerivationIndexAccounts,
  removePersistedWalletConnectSlice,
  removeProviders,
  removeReplaceAccountOptions,
  removeShowSmallBalances,
  removeTokenListsAndCustomTokens,
  removeTokensMetadataDisplayType,
  removeWalletConnectModalState,
  renameFollowedAddressesToWatchedAddresses,
  resetActiveChains,
  resetEnsApi,
  resetLastTxNotificationUpdate,
  resetOnboardingStateForGA,
  resetPushNotificationsEnabled,
  resetTokensOrderBy,
  resetTokensOrderByAndMetadataDisplayType,
  restructureTransactionsAndNotifications,
  transformNotificationCountToStatus,
  updateLanguageSettings,
} from 'src/app/mobileMigrations'
import {
  addActivityVisibility,
  addDismissedBridgedAndCompatibleWarnings,
  migrateDismissedTokenWarnings,
  migrateSearchHistory,
  removeThaiBahtFromFiatCurrency,
  unchecksumDismissedTokenWarningKeys,
} from 'uniswap/src/state/uniswapMigrations'
import {
  activatePendingAccounts,
  addBatchedTransactions,
  addCreatedOnboardingRedesignAccountBehaviorHistory,
  addExploreAndWelcomeBehaviorHistory,
  addHapticSetting,
  addRoutingFieldToTransactions,
  deleteBetaOnboardingState,
  deleteDefaultFavoritesFromFavoritesState,
  deleteExtensionOnboardingState,
  deleteHoldToSwapBehaviorHistory,
  deleteWelcomeWalletCardBehaviorHistory,
  migrateLiquidityTransactionInfo,
  moveCurrencySetting,
  moveDismissedTokenWarnings,
  moveHapticsToUserSettings,
  moveLanguageSetting,
  moveTokenAndNFTVisibility,
  moveUserSettings,
  removeCreatedOnboardingRedesignAccountBehaviorHistory,
  removePriceAlertsEnabledFromPushNotifications,
  removeUniconV2BehaviorState,
  removeWalletIsUnlockedState,
  updateExploreOrderByType,
} from 'wallet/src/state/walletMigrations'

export const migrations = {
  0: restructureTransactionsAndNotifications,
  1: removeWalletConnectModalState,
  2: renameFollowedAddressesToWatchedAddresses,
  3: addSearchHistory,
  4: addTimeImportedAndDerivationIndex,
  5: addModalsState,
  6: addWalletConnectPendingSessionAndSettings,
  7: removeNonZeroDerivationIndexAccounts,
  8: addCloudBackup,
  9: removeLocalTypeAccounts,
  10: removeDemoAccount,
  11: addBiometricSettings,
  12: addPushNotificationsEnabledToAccounts,
  13: addEnsState,
  14: migrateBiometricSettings,
  15: changeNativeTypeToSignerMnemonic,
  16: removeDataApi,
  17: resetPushNotificationsEnabled,
  18: removeEnsState,
  19: filterToSupportedChains,
  20: resetLastTxNotificationUpdate,
  21: addExperimentsSlice,
  22: removeCoingeckoApiAndTokenLists,
  23: resetTokensOrderByAndMetadataDisplayType,
  24: transformNotificationCountToStatus,
  25: addPasswordLockout,
  26: removeShowSmallBalances,
  27: resetTokensOrderBy,
  28: removeTokensMetadataDisplayType,
  29: removeTokenListsAndCustomTokens,
  30: migrateFiatPurchaseTransactionInfo,
  31: emptyMigration,
  32: resetEnsApi,
  33: addReplaceAccountOptions,
  34: addLastBalancesReport,
  35: addAppearanceSetting,
  36: addHiddenNfts,
  37: correctFailedFiatOnRampTxIds,
  38: removeReplaceAccountOptions,
  39: removeExperimentsSlice,
  40: removePersistedWalletConnectSlice,
  41: addLastBalancesReportValue,
  42: removeFlashbotsEnabledFromWalletSlice,
  43: convertHiddenNftsToNftsData,
  44: removeProviders,
  45: addTokensVisibility,
  46: deleteRTKQuerySlices,
  47: resetActiveChains,
  48: addTweaksStartingState,
  49: addSwapProtectionSetting,
  50: deleteChainsSlice,
  51: addLanguageSettings,
  52: addFiatCurrencySettings,
  53: updateLanguageSettings,
  54: addWalletIsFunded,
  55: addBehaviorHistory,
  56: addAllowAnalyticsSwitch,
  57: moveSettingStateToGlobal,
  58: addSkippedUnitagBoolean,
  59: addCompletedUnitagsIntroBoolean,
  60: addUniconV2IntroModalBoolean,
  61: flattenTokenVisibility,
  62: addExtensionOnboardingState,
  63: removeWalletIsUnlockedState,
  64: removeUniconV2BehaviorState,
  65: addRoutingFieldToTransactions,
  66: activatePendingAccounts,
  67: resetOnboardingStateForGA,
  68: deleteBetaOnboardingState,
  69: deleteExtensionOnboardingState,
  70: deleteDefaultFavoritesFromFavoritesState,
  71: addHapticSetting,
  72: addExploreAndWelcomeBehaviorHistory,
  73: moveUserSettings,
  74: deleteOldOnRampTxData,
  75: deleteHoldToSwapBehaviorHistory,
  76: addCreatedOnboardingRedesignAccountBehaviorHistory,
  77: moveDismissedTokenWarnings,
  78: moveLanguageSetting,
  79: moveCurrencySetting,
  80: updateExploreOrderByType,
  81: removeCreatedOnboardingRedesignAccountBehaviorHistory,
  82: unchecksumDismissedTokenWarningKeys,
  83: addPushNotifications,
  84: deleteWelcomeWalletCardBehaviorHistory,
  85: moveTokenAndNFTVisibility,
  86: addBatchedTransactions,
  87: migrateDappRequestInfoTypes,
  88: moveHapticsToUserSettings,
  89: removeThaiBahtFromFiatCurrency,
  90: migrateLiquidityTransactionInfo,
  91: removePriceAlertsEnabledFromPushNotifications,
  92: migrateAndRemoveCloudBackupSlice,
  93: migrateSearchHistory,
  94: addDismissedBridgedAndCompatibleWarnings,
  95: addActivityVisibility,
  96: migrateDismissedTokenWarnings,
}

export const MOBILE_STATE_VERSION = 96
