/* eslint-disable @typescript-eslint/no-require-imports */
export const ETHEREUM_LOGO = require('./logos/ethereum-logo.png')
export const OPTIMISM_LOGO = require('./logos/optimism-logo.png')
export const ARBITRUM_LOGO = require('./logos/arbitrum-logo.png')
export const POLYGON_LOGO = require('./logos/polygon-matic-logo.png')
export const GOERLI_LOGO = require('./logos/goerli-logo.png')
export const MUMBAI_LOGO = require('./logos/mumbai-logo.png')
export const UNISWAP_SPLASH_LOGO = require('./logos/uniswap-splash-logo.png')
export const FAVORITE_TOKENS_EMPTY_BG = require('./backgrounds/favorite-tokens-bg.png')
export const WATCHED_TOKENS_EMPTY_BG = require('./backgrounds/watched-tokens-bg.png')
export const LANDING_BACKGROUND_LIGHT = require('./backgrounds/landingBackgroundLight.png')
export const LANDING_BACKGROUND_DARK = require('./backgrounds/landingBackgroundDark.png')
export const LANDING_BLUR_BACKGROUND_LIGHT = require('./backgrounds/landingBlurBackgroundLight.png')
export const LANDING_BLUR_BACKGROUND_DARK = require('./backgrounds/landingBlurBackgroundDark.png')
export const UNISWAP_LOGO = require('./logos/uniswap-logo.png')
export const ONBOARDING_QR_ETCHING_VIDEO = require('./videos/etching.mp4')
