import userEvent from '@testing-library/user-event'
import { HookEntry, HookFlags } from '@uniswap/client-liquidity/dist/uniswap/liquidity/v2/types_pb'
import { UniswapBuiltHookAddressesConfigKey, useDynamicConfigValue } from '@universe/gating'
import { TestID } from '@universe/test'
import { Link } from 'react-router'
import { shortenAddress } from 'utilities/src/addresses'
import { afterEach, describe, expect, it, vi } from 'vitest'
import { HookDetailsModal } from '~/features/Liquidity/HookDetailsModal'
import { render, screen } from '~/test-utils/render'

const BASE_HOOK = new HookEntry({
  address: '0x1234567890abcdef1234567890abcdef12345678',
  chain: 'Base',
  chainId: 8453,
  name: 'TestHook',
  description: 'Adjusts LP fees dynamically',
  verifiedSource: true,
  flags: new HookFlags({ beforeSwap: true, afterSwap: true }),
})

function renderModal(hookEntry: HookEntry) {
  return render(<HookDetailsModal hookEntry={hookEntry} chainId={8453} isOpen onClose={vi.fn()} />)
}

// PoolTable and the position rows open this modal from a cell inside a react-router <Link>. The dialog
// is portaled out of that anchor in the DOM, but React synthetic clicks still bubble through the portal
// to the Link, which navigates on any click nothing stopped.
const ROW_LINK_PATH = '/explore/pools/ethereum/0xpool'
function renderModalInsideRowLink(hookEntry: HookEntry) {
  return render(
    <Link to={ROW_LINK_PATH}>
      <HookDetailsModal hookEntry={hookEntry} chainId={8453} isOpen onClose={vi.fn()} />
    </Link>,
  )
}

// A navigation leaked by one test must not decide the next one's starting path.
afterEach(() => {
  window.history.replaceState({}, '', '/')
})

// Serves the hook under one list of the `uniswap_built_hook_addresses` config; the other two stay empty.
function listHookUnder(listKey: UniswapBuiltHookAddressesConfigKey) {
  vi.mocked(useDynamicConfigValue).mockImplementation(((args: { key: string; defaultValue: unknown }) =>
    args.key === listKey
      ? [{ chainId: BASE_HOOK.chainId, address: BASE_HOOK.address }]
      : args.defaultValue) as typeof useDynamicConfigValue)
}

describe('HookDetailsModal', () => {
  it('renders hook name as the title', () => {
    renderModal(BASE_HOOK)
    expect(screen.getByText('TestHook')).toBeTruthy()
  })

  it('falls back to shortened address when name is empty', () => {
    const hookNoName = new HookEntry({
      ...BASE_HOOK,
      name: '',
    })
    renderModal(hookNoName)
    expect(screen.queryByText('TestHook')).toBeNull()
    expect(screen.getAllByText(/0x1234/).length).toBeGreaterThan(0)
  })

  it('renders chain name', () => {
    renderModal(BASE_HOOK)
    expect(screen.getByText('Base')).toBeTruthy()
  })

  it('renders the address middle-ellipsized, not in full', () => {
    renderModal(BASE_HOOK)
    const ellipsized = shortenAddress({ address: BASE_HOOK.address, chars: 14, charsEnd: 8 })
    expect(ellipsized).toContain('...')
    expect(screen.getByText(ellipsized)).toBeTruthy()
    expect(screen.queryByText(BASE_HOOK.address)).toBeNull()
  })

  it('does not render an explorer link', () => {
    renderModal(BASE_HOOK)
    expect(screen.queryByText('View on Explorer')).toBeNull()
  })

  it('renders description with the AI-generated caption', () => {
    renderModal(BASE_HOOK)
    expect(screen.getByText('Adjusts LP fees dynamically')).toBeTruthy()
    expect(screen.getByText('Description generated by AI')).toBeTruthy()
  })

  it('does not render description or its caption when empty', () => {
    const hookNoDesc = new HookEntry({
      ...BASE_HOOK,
      description: '',
    })
    renderModal(hookNoDesc)
    expect(screen.queryByText('Adjusts LP fees dynamically')).toBeNull()
    expect(screen.queryByText('Description generated by AI')).toBeNull()
  })

  it('renders active flag pills', () => {
    renderModal(BASE_HOOK)
    expect(screen.getByText('beforeSwap')).toBeTruthy()
    expect(screen.getByText('afterSwap')).toBeTruthy()
  })

  it('does not render inactive flags', () => {
    renderModal(BASE_HOOK)
    expect(screen.queryByText('beforeInitialize')).toBeNull()
    expect(screen.queryByText('afterAddLiquidity')).toBeNull()
  })

  it('does not render flags section when no flags are active', () => {
    const hookNoFlags = new HookEntry({
      ...BASE_HOOK,
      flags: new HookFlags({}),
    })
    renderModal(hookNoFlags)
    expect(screen.queryByText('beforeSwap')).toBeNull()
  })

  describe('Uniswap provenance badge', () => {
    // useDynamicConfigValue is mocked globally in setupTests to return the passed defaultValue. These
    // render the Uniswap mark too — with the setup's fail-on-console, passing also pins that the mark's
    // fixed chip colour emits no mycelium compat diagnostic.
    afterEach(() => {
      vi.mocked(useDynamicConfigValue).mockImplementation(
        ((args: { defaultValue: unknown }) => args.defaultValue) as typeof useDynamicConfigValue,
      )
    })

    it('renders no badge for a hook the config does not list', () => {
      renderModal(BASE_HOOK)
      expect(screen.queryByText(/by Uniswap/)).toBeNull()
      expect(screen.queryByTestId(TestID.HookProvenanceInfo)).toBeNull()
    })

    // The badge keys on the chain the modal displays, not the registry entry's self-reported chainId.
    it('renders no badge when the displayed chain is not the listed one', () => {
      listHookUnder(UniswapBuiltHookAddressesConfigKey.Built)
      render(<HookDetailsModal hookEntry={BASE_HOOK} chainId={1} isOpen onClose={vi.fn()} />)
      expect(screen.queryByText(/by Uniswap/)).toBeNull()
    })

    it.each([
      [UniswapBuiltHookAddressesConfigKey.Built, 'Built by Uniswap'],
      [UniswapBuiltHookAddressesConfigKey.Configured, 'Configured by Uniswap'],
      [UniswapBuiltHookAddressesConfigKey.Both, 'Built and configured by Uniswap'],
    ])('badges a hook in the config\'s %s list as "%s"', (listKey, label) => {
      listHookUnder(listKey)
      renderModal(BASE_HOOK)
      expect(screen.getByText(label)).toBeTruthy()
    })

    it.each([
      [UniswapBuiltHookAddressesConfigKey.Built, 'Uniswap Labs developed this hook.'],
      [UniswapBuiltHookAddressesConfigKey.Configured, 'Uniswap Labs set this hook’s configuration.'],
      [UniswapBuiltHookAddressesConfigKey.Both, 'Uniswap Labs developed this hook and set its configuration.'],
    ])('explains the %s badge and links to the help center when the badge is hovered', async (listKey, description) => {
      listHookUnder(listKey)
      renderModal(BASE_HOOK)

      await userEvent.hover(screen.getByTestId(TestID.HookProvenanceInfo))

      expect(await screen.findByText(description)).toBeInTheDocument()
      expect(screen.getByText('Learn more')).toBeInTheDocument()
    })

    // The tooltip popup is portaled even further out than the dialog; a click on its "Learn more" anchor
    // must not reach the row link either, or it opens the pool page instead of the article.
    it("does not navigate the row link when the tooltip's Learn more link is clicked", async () => {
      listHookUnder(UniswapBuiltHookAddressesConfigKey.Built)
      renderModalInsideRowLink(BASE_HOOK)

      await userEvent.hover(screen.getByTestId(TestID.HookProvenanceInfo))
      await userEvent.click(await screen.findByText('Learn more'))

      expect(window.location.pathname).toBe('/')
    })
  })

  describe('opened from inside a row link', () => {
    it('does not navigate the row link when content inside the modal is clicked', async () => {
      renderModalInsideRowLink(BASE_HOOK)

      await userEvent.click(screen.getByText('Adjusts LP fees dynamically'))

      expect(window.location.pathname).toBe('/')
    })
  })
})
