import { HookEntry, HookFlags } from '@uniswap/client-liquidity/dist/uniswap/liquidity/v2/types_pb'
import { shortenAddress } from 'utilities/src/addresses'
import { describe, expect, it, vi } from 'vitest'
import { HookDetailsModal } from '~/features/Liquidity/HookDetailsModal'
import { render, screen } from '~/test-utils/render'

const BASE_HOOK = new HookEntry({
  address: '0x1234567890abcdef1234567890abcdef12345678',
  chain: 'Base',
  chainId: 8453,
  name: 'TestHook',
  description: 'Adjusts LP fees dynamically',
  verifiedSource: true,
  flags: new HookFlags({ beforeSwap: true, afterSwap: true }),
})

function renderModal(hookEntry: HookEntry) {
  return render(<HookDetailsModal hookEntry={hookEntry} chainId={8453} isOpen onClose={vi.fn()} />)
}

describe('HookDetailsModal', () => {
  it('renders hook name as the title', () => {
    renderModal(BASE_HOOK)
    expect(screen.getByText('TestHook')).toBeTruthy()
  })

  it('falls back to shortened address when name is empty', () => {
    const hookNoName = new HookEntry({
      ...BASE_HOOK,
      name: '',
    })
    renderModal(hookNoName)
    expect(screen.queryByText('TestHook')).toBeNull()
    expect(screen.getAllByText(/0x1234/).length).toBeGreaterThan(0)
  })

  it('renders chain name', () => {
    renderModal(BASE_HOOK)
    expect(screen.getByText('Base')).toBeTruthy()
  })

  it('renders the address middle-ellipsized, not in full', () => {
    renderModal(BASE_HOOK)
    const ellipsized = shortenAddress({ address: BASE_HOOK.address, chars: 14, charsEnd: 8 })
    expect(ellipsized).toContain('...')
    expect(screen.getByText(ellipsized)).toBeTruthy()
    expect(screen.queryByText(BASE_HOOK.address)).toBeNull()
  })

  it('does not render an explorer link', () => {
    renderModal(BASE_HOOK)
    expect(screen.queryByText('View on Explorer')).toBeNull()
  })

  it('renders description with the AI-generated caption', () => {
    renderModal(BASE_HOOK)
    expect(screen.getByText('Adjusts LP fees dynamically')).toBeTruthy()
    expect(screen.getByText('Description generated by AI')).toBeTruthy()
  })

  it('does not render description or its caption when empty', () => {
    const hookNoDesc = new HookEntry({
      ...BASE_HOOK,
      description: '',
    })
    renderModal(hookNoDesc)
    expect(screen.queryByText('Adjusts LP fees dynamically')).toBeNull()
    expect(screen.queryByText('Description generated by AI')).toBeNull()
  })

  it('renders active flag pills', () => {
    renderModal(BASE_HOOK)
    expect(screen.getByText('beforeSwap')).toBeTruthy()
    expect(screen.getByText('afterSwap')).toBeTruthy()
  })

  it('does not render inactive flags', () => {
    renderModal(BASE_HOOK)
    expect(screen.queryByText('beforeInitialize')).toBeNull()
    expect(screen.queryByText('afterAddLiquidity')).toBeNull()
  })

  it('does not render flags section when no flags are active', () => {
    const hookNoFlags = new HookEntry({
      ...BASE_HOOK,
      flags: new HookFlags({}),
    })
    renderModal(hookNoFlags)
    expect(screen.queryByText('beforeSwap')).toBeNull()
  })
})
