export const MORPHO_ABI = [
  {
    inputs: [
      {
        components: [
          { name: 'loanToken', type: 'address' },
          { name: 'collateralToken', type: 'address' },
          { name: 'oracle', type: 'address' },
          { name: 'irm', type: 'address' },
          { name: 'lltv', type: 'uint256' },
        ],
        name: 'marketParams',
        type: 'tuple' as const,
      },
      { name: 'assets', type: 'uint256' },
      { name: 'onBehalf', type: 'address' },
      { name: 'data', type: 'bytes' },
    ],
    name: 'supplyCollateral',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function' as const,
  },
  {
    inputs: [
      {
        components: [
          { name: 'loanToken', type: 'address' },
          { name: 'collateralToken', type: 'address' },
          { name: 'oracle', type: 'address' },
          { name: 'irm', type: 'address' },
          { name: 'lltv', type: 'uint256' },
        ],
        name: 'marketParams',
        type: 'tuple' as const,
      },
      { name: 'assets', type: 'uint256' },
      { name: 'shares', type: 'uint256' },
      { name: 'onBehalf', type: 'address' },
      { name: 'receiver', type: 'address' },
    ],
    name: 'borrow',
    outputs: [
      { name: 'assetsBorrowed', type: 'uint256' },
      { name: 'sharesBorrowed', type: 'uint256' },
    ],
    stateMutability: 'nonpayable',
    type: 'function' as const,
  },
  {
    inputs: [
      {
        components: [
          { name: 'loanToken', type: 'address' },
          { name: 'collateralToken', type: 'address' },
          { name: 'oracle', type: 'address' },
          { name: 'irm', type: 'address' },
          { name: 'lltv', type: 'uint256' },
        ],
        name: 'marketParams',
        type: 'tuple' as const,
      },
      { name: 'assets', type: 'uint256' },
      { name: 'shares', type: 'uint256' },
      { name: 'onBehalf', type: 'address' },
      { name: 'data', type: 'bytes' },
    ],
    name: 'repay',
    outputs: [
      { name: 'assetsRepaid', type: 'uint256' },
      { name: 'sharesRepaid', type: 'uint256' },
    ],
    stateMutability: 'nonpayable',
    type: 'function' as const,
  },
  {
    inputs: [
      {
        components: [
          { name: 'loanToken', type: 'address' },
          { name: 'collateralToken', type: 'address' },
          { name: 'oracle', type: 'address' },
          { name: 'irm', type: 'address' },
          { name: 'lltv', type: 'uint256' },
        ],
        name: 'marketParams',
        type: 'tuple' as const,
      },
      { name: 'assets', type: 'uint256' },
      { name: 'onBehalf', type: 'address' },
      { name: 'receiver', type: 'address' },
    ],
    name: 'withdrawCollateral',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function' as const,
  },
  {
    inputs: [
      {
        components: [
          { name: 'loanToken', type: 'address' },
          { name: 'collateralToken', type: 'address' },
          { name: 'oracle', type: 'address' },
          { name: 'irm', type: 'address' },
          { name: 'lltv', type: 'uint256' },
        ],
        name: 'marketParams',
        type: 'tuple' as const,
      },
      { name: 'assets', type: 'uint256' },
      { name: 'shares', type: 'uint256' },
      { name: 'onBehalf', type: 'address' },
      { name: 'data', type: 'bytes' },
    ],
    name: 'supply',
    outputs: [
      { name: 'assetsSupplied', type: 'uint256' },
      { name: 'sharesSupplied', type: 'uint256' },
    ],
    stateMutability: 'nonpayable',
    type: 'function' as const,
  },
  {
    inputs: [
      {
        components: [
          { name: 'loanToken', type: 'address' },
          { name: 'collateralToken', type: 'address' },
          { name: 'oracle', type: 'address' },
          { name: 'irm', type: 'address' },
          { name: 'lltv', type: 'uint256' },
        ],
        name: 'marketParams',
        type: 'tuple' as const,
      },
      { name: 'assets', type: 'uint256' },
      { name: 'shares', type: 'uint256' },
      { name: 'onBehalf', type: 'address' },
      { name: 'receiver', type: 'address' },
    ],
    name: 'withdraw',
    outputs: [
      { name: 'assetsWithdrawn', type: 'uint256' },
      { name: 'sharesWithdrawn', type: 'uint256' },
    ],
    stateMutability: 'nonpayable',
    type: 'function' as const,
  },
  {
    inputs: [
      { name: 'id', type: 'bytes32' },
      { name: 'user', type: 'address' },
    ],
    name: 'position',
    outputs: [
      { name: 'supplyShares', type: 'uint256' },
      { name: 'borrowShares', type: 'uint128' },
      { name: 'collateral', type: 'uint128' },
    ],
    stateMutability: 'view',
    type: 'function' as const,
  },
  {
    inputs: [{ name: 'id', type: 'bytes32' }],
    name: 'idToMarketParams',
    outputs: [
      { name: 'loanToken', type: 'address' },
      { name: 'collateralToken', type: 'address' },
      { name: 'oracle', type: 'address' },
      { name: 'irm', type: 'address' },
      { name: 'lltv', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function' as const,
  },
  {
    inputs: [{ name: 'id', type: 'bytes32' }],
    name: 'market',
    outputs: [
      { name: 'totalSupplyAssets', type: 'uint128' },
      { name: 'totalSupplyShares', type: 'uint128' },
      { name: 'totalBorrowAssets', type: 'uint128' },
      { name: 'totalBorrowShares', type: 'uint128' },
      { name: 'lastUpdate', type: 'uint128' },
      { name: 'fee', type: 'uint128' },
    ],
    stateMutability: 'view',
    type: 'function' as const,
  },
  {
    inputs: [
      { name: 'authorizer', type: 'address' },
      { name: 'authorized', type: 'address' },
    ],
    name: 'isAuthorized',
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function' as const,
  },
  {
    inputs: [
      { name: 'authorized', type: 'address' },
      { name: 'newIsAuthorized', type: 'bool' },
    ],
    name: 'setAuthorization',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function' as const,
  },
] as const

export const ERC20_ABI = [
  {
    inputs: [
      { name: 'spender', type: 'address' },
      { name: 'amount', type: 'uint256' },
    ],
    name: 'approve',
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'nonpayable',
    type: 'function' as const,
  },
  {
    inputs: [
      { name: 'owner', type: 'address' },
      { name: 'spender', type: 'address' },
    ],
    name: 'allowance',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function' as const,
  },
  {
    inputs: [{ name: 'account', type: 'address' }],
    name: 'balanceOf',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function' as const,
  },
  {
    inputs: [],
    name: 'name',
    outputs: [{ name: '', type: 'string' }],
    stateMutability: 'view',
    type: 'function' as const,
  },
  {
    inputs: [],
    name: 'symbol',
    outputs: [{ name: '', type: 'string' }],
    stateMutability: 'view',
    type: 'function' as const,
  },
  {
    inputs: [],
    name: 'decimals',
    outputs: [{ name: '', type: 'uint8' }],
    stateMutability: 'view',
    type: 'function' as const,
  },
] as const

export const VAULT_ABI = [
  {
    inputs: [],
    name: 'name',
    outputs: [{ name: '', type: 'string' }],
    stateMutability: 'view',
    type: 'function' as const,
  },
  {
    inputs: [],
    name: 'symbol',
    outputs: [{ name: '', type: 'string' }],
    stateMutability: 'view',
    type: 'function' as const,
  },
  {
    inputs: [],
    name: 'decimals',
    outputs: [{ name: '', type: 'uint8' }],
    stateMutability: 'view',
    type: 'function' as const,
  },
  {
    inputs: [],
    name: 'asset',
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function' as const,
  },
  {
    inputs: [
      { name: 'assets', type: 'uint256' },
      { name: 'receiver', type: 'address' },
    ],
    name: 'deposit',
    outputs: [{ name: 'shares', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function' as const,
  },
  {
    inputs: [
      { name: 'assets', type: 'uint256' },
      { name: 'receiver', type: 'address' },
      { name: 'owner', type: 'address' },
    ],
    name: 'withdraw',
    outputs: [{ name: 'shares', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function' as const,
  },
  {
    inputs: [{ name: 'account', type: 'address' }],
    name: 'balanceOf',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function' as const,
  },
  {
    inputs: [{ name: 'id', type: 'bytes32' }],
    name: 'config',
    outputs: [
      { name: 'cap', type: 'uint184' },
      { name: 'enabled', type: 'bool' },
      { name: 'removableAt', type: 'uint64' },
    ],
    stateMutability: 'view',
    type: 'function' as const,
  },
  {
    inputs: [{ name: 'shares', type: 'uint256' }],
    name: 'convertToAssets',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function' as const,
  },
  {
    inputs: [],
    name: 'curator',
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function' as const,
  },
  {
    inputs: [],
    name: 'fee',
    outputs: [{ name: '', type: 'uint96' }],
    stateMutability: 'view',
    type: 'function' as const,
  },
  {
    inputs: [{ name: 'assets', type: 'uint256' }],
    name: 'previewWithdraw',
    outputs: [{ name: 'shares', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function' as const,
  },
  {
    inputs: [],
    name: 'totalAssets',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function' as const,
  },
  {
    inputs: [],
    name: 'totalSupply',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function' as const,
  },
  {
    inputs: [{ name: 'index', type: 'uint256' }],
    name: 'supplyQueue',
    outputs: [{ name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function' as const,
  },
  {
    inputs: [],
    name: 'supplyQueueLength',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function' as const,
  },
  {
    inputs: [{ name: 'index', type: 'uint256' }],
    name: 'withdrawQueue',
    outputs: [{ name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function' as const,
  },
  {
    inputs: [],
    name: 'withdrawQueueLength',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function' as const,
  },
  {
    inputs: [{ name: 'owner', type: 'address' }],
    name: 'maxWithdraw',
    outputs: [{ name: 'assets', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function' as const,
  },
  {
    inputs: [{ name: 'owner', type: 'address' }],
    name: 'maxRedeem',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function' as const,
  },
] as const

export const ORACLE_ABI = [
  {
    inputs: [],
    name: 'price',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function' as const,
  },
] as const

export const IRM_ABI = [
  {
    inputs: [
      {
        components: [
          { name: 'loanToken', type: 'address' },
          { name: 'collateralToken', type: 'address' },
          { name: 'oracle', type: 'address' },
          { name: 'irm', type: 'address' },
          { name: 'lltv', type: 'uint256' },
        ],
        name: 'marketParams',
        type: 'tuple' as const,
      },
      {
        components: [
          { name: 'totalSupplyAssets', type: 'uint128' },
          { name: 'totalSupplyShares', type: 'uint128' },
          { name: 'totalBorrowAssets', type: 'uint128' },
          { name: 'totalBorrowShares', type: 'uint128' },
          { name: 'lastUpdate', type: 'uint128' },
          { name: 'fee', type: 'uint128' },
        ],
        name: 'market',
        type: 'tuple' as const,
      },
    ],
    name: 'borrowRateView',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function' as const,
  },
] as const

export const FEWTOKEN_ROUTER_ABI = [
  {
    inputs: [],
    name: 'guardian',
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function' as const,
  },
  {
    inputs: [],
    name: 'pendingGuardian',
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function' as const,
  },
  {
    inputs: [{ name: 'newGuardian', type: 'address' }],
    name: 'submitGuardian',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function' as const,
  },
  {
    inputs: [],
    name: 'acceptGuardian',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function' as const,
  },
  {
    inputs: [],
    name: 'paused',
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function' as const,
  },
  {
    inputs: [],
    name: 'pause',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function' as const,
  },
  {
    inputs: [],
    name: 'unpause',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function' as const,
  },
  {
    inputs: [],
    name: 'morpho',
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function' as const,
  },
  {
    inputs: [{ name: '', type: 'address' }],
    name: 'isSupportedVault',
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function' as const,
  },
  {
    inputs: [
      { name: 'vault', type: 'address' },
      { name: 'newIsSupported', type: 'bool' },
    ],
    name: 'setSupportedVault',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function' as const,
  },
  {
    inputs: [{ name: '', type: 'bytes32' }],
    name: 'isSupportedMarket',
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function' as const,
  },
  {
    inputs: [
      { name: 'marketId', type: 'bytes32' },
      { name: 'newIsSupported', type: 'bool' },
    ],
    name: 'setSupportedMarket',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function' as const,
  },
  {
    inputs: [
      { name: 'marketId', type: 'bytes32' },
      { name: 'wrapper', type: 'address' },
      { name: 'underlyingAmount', type: 'uint256' },
    ],
    name: 'supplyCollateralWithWrap',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function' as const,
  },
  {
    inputs: [
      { name: 'marketId', type: 'bytes32' },
      { name: 'wrapper', type: 'address' },
      { name: 'borrowAssets', type: 'uint256' },
    ],
    name: 'borrowAndUnwrap',
    outputs: [
      { name: 'assetsBorrowed', type: 'uint256' },
      { name: 'sharesBorrowed', type: 'uint256' },
    ],
    stateMutability: 'nonpayable',
    type: 'function' as const,
  },
  {
    inputs: [
      { name: 'marketId', type: 'bytes32' },
      { name: 'wrapper', type: 'address' },
      { name: 'underlyingAmount', type: 'uint256' },
    ],
    name: 'repayWithWrap',
    outputs: [
      { name: 'assetsRepaid', type: 'uint256' },
      { name: 'sharesRepaid', type: 'uint256' },
    ],
    stateMutability: 'nonpayable',
    type: 'function' as const,
  },
  {
    inputs: [
      { name: 'marketId', type: 'bytes32' },
      { name: 'wrapper', type: 'address' },
      { name: 'collateralAssets', type: 'uint256' },
    ],
    name: 'withdrawCollateralAndUnwrap',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function' as const,
  },
  {
    inputs: [
      { name: 'vault', type: 'address' },
      { name: 'wrapper', type: 'address' },
      { name: 'underlyingAmount', type: 'uint256' },
    ],
    name: 'vaultDepositWithWrap',
    outputs: [{ name: 'shares', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function' as const,
  },
  {
    inputs: [
      { name: 'vault', type: 'address' },
      { name: 'wrapper', type: 'address' },
      { name: 'assets', type: 'uint256' },
    ],
    name: 'vaultWithdrawAndUnwrap',
    outputs: [{ name: 'shares', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function' as const,
  },
  {
    inputs: [
      { name: 'vault', type: 'address' },
      { name: 'wrapper', type: 'address' },
      { name: 'shares', type: 'uint256' },
    ],
    name: 'vaultRedeemAndUnwrap',
    outputs: [{ name: 'assets', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function' as const,
  },
] as const
