/**
 * Long-tail style-prop tables for the Tamagui-compatible Flex.
 *
 * Props listed here have no bespoke utility mapping in `compile.ts`; they
 * compile generically to Tailwind arbitrary-property utilities
 * (`[aspect-ratio:2]`, `[cursor:pointer]`, …) so the full RN + Tamagui web
 * style surface stays expressible without enumerating a utility per property.
 */

/** Properties whose numeric values are unitless in CSS (no `px` suffix). */
export const UNITLESS_STYLE_PROPS: ReadonlySet<string> = new Set([
  'aspectRatio',
  'flex',
  'flexGrow',
  'flexShrink',
  'gridColumn',
  'gridColumnEnd',
  'gridColumnStart',
  'gridRow',
  'gridRowEnd',
  'gridRowStart',
  'opacity',
  'shadowOpacity',
  'zIndex',
])

/**
 * RN/Tamagui prop → CSS property name where plain camelCase → kebab-case
 * hyphenation is not the correct translation (react-native-web mappings).
 */
export const CSS_PROP_NAME_OVERRIDES: Readonly<Record<string, string>> = {
  borderBottomEndRadius: 'border-end-end-radius',
  borderBottomStartRadius: 'border-end-start-radius',
  borderTopEndRadius: 'border-start-end-radius',
  borderTopStartRadius: 'border-start-start-radius',
  borderEndColor: 'border-inline-end-color',
  borderEndWidth: 'border-inline-end-width',
  borderStartColor: 'border-inline-start-color',
  borderStartWidth: 'border-inline-start-width',
  end: 'inset-inline-end',
  start: 'inset-inline-start',
  marginEnd: 'margin-inline-end',
  marginStart: 'margin-inline-start',
  paddingEnd: 'padding-inline-end',
  paddingStart: 'padding-inline-start',
}

/**
 * The generic long-tail surface: every remaining RN `ViewStyle` / Tamagui
 * web-extra style prop the compiler accepts with `string | number` values.
 * Grouped by origin; each compiles to `[css-prop:value]`.
 */
export const LONG_TAIL_STYLE_PROPS = [
  // RN ViewStyle
  'backfaceVisibility',
  'borderBlockColor',
  'borderBlockEndColor',
  'borderBlockStartColor',
  'borderBottomColor',
  'borderBottomEndRadius',
  'borderBottomLeftRadius',
  'borderBottomRightRadius',
  'borderBottomStartRadius',
  'borderCurve',
  'borderEndColor',
  'borderEndEndRadius',
  'borderEndStartRadius',
  'borderEndWidth',
  'borderLeftColor',
  'borderRightColor',
  'borderStartColor',
  'borderStartEndRadius',
  'borderStartStartRadius',
  'borderStartWidth',
  'borderStyle',
  'borderTopColor',
  'borderTopEndRadius',
  'borderTopLeftRadius',
  'borderTopRightRadius',
  'borderTopStartRadius',
  'boxSizing',
  'cursor',
  'direction',
  'end',
  'isolation',
  'marginEnd',
  'marginStart',
  'paddingEnd',
  'paddingStart',
  'pointerEvents',
  'start',
  // RN + Tamagui web extras (CSS pass-through surface)
  'alignContent',
  'aspectRatio',
  'backdropFilter',
  'background',
  'backgroundAttachment',
  'backgroundBlendMode',
  'backgroundClip',
  'backgroundImage',
  'backgroundOrigin',
  'backgroundPosition',
  'backgroundRepeat',
  'backgroundSize',
  'blockSize',
  'borderBlockEndStyle',
  'borderBlockEndWidth',
  'borderBlockStartStyle',
  'borderBlockStartWidth',
  'borderBlockStyle',
  'borderBlockWidth',
  'borderImage',
  'borderInlineColor',
  'borderInlineEndColor',
  'borderInlineEndStyle',
  'borderInlineEndWidth',
  'borderInlineStartColor',
  'borderInlineStartStyle',
  'borderInlineStartWidth',
  'borderInlineStyle',
  'borderInlineWidth',
  'caretColor',
  'clipPath',
  'contain',
  'containerType',
  'content',
  'filter',
  'float',
  'gridColumn',
  'gridColumnEnd',
  'gridColumnGap',
  'gridColumnStart',
  'gridRow',
  'gridRowEnd',
  'gridRowGap',
  'gridRowStart',
  'gridTemplateAreas',
  'gridTemplateColumns',
  'inlineSize',
  'insetBlock',
  'insetBlockEnd',
  'insetBlockStart',
  'insetInline',
  'insetInlineEnd',
  'insetInlineStart',
  'marginBlock',
  'marginBlockEnd',
  'marginBlockStart',
  'marginInline',
  'marginInlineEnd',
  'marginInlineStart',
  'mask',
  'maskBorder',
  'maskBorderMode',
  'maskBorderOutset',
  'maskBorderRepeat',
  'maskBorderSlice',
  'maskBorderSource',
  'maskBorderWidth',
  'maskClip',
  'maskComposite',
  'maskImage',
  'maskMode',
  'maskOrigin',
  'maskPosition',
  'maskRepeat',
  'maskSize',
  'maskType',
  'maxBlockSize',
  'maxInlineSize',
  'minBlockSize',
  'minInlineSize',
  'mixBlendMode',
  'objectFit',
  'outlineColor',
  'outlineOffset',
  'outlineStyle',
  'outlineWidth',
  'overflowBlock',
  'overflowInline',
  'overflowX',
  'overflowY',
  'paddingBlock',
  'paddingBlockEnd',
  'paddingBlockStart',
  'paddingInline',
  'paddingInlineEnd',
  'paddingInlineStart',
  'scrollbarWidth',
  'textEmphasis',
  'textWrap',
  'touchAction',
  'transformStyle',
  'transition',
  'userSelect',
  'verticalAlign',
] as const

export type LongTailStyleProp = (typeof LONG_TAIL_STYLE_PROPS)[number]

export const LONG_TAIL_STYLE_PROP_SET: ReadonlySet<string> = new Set(LONG_TAIL_STYLE_PROPS)

/** Convert a camelCase style prop to its CSS property name. */
export function cssPropertyName(prop: string): string {
  return CSS_PROP_NAME_OVERRIDES[prop] ?? prop.replace(/[A-Z]/g, (match) => `-${match.toLowerCase()}`)
}
