name: Check PR Title

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  semantic-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v3.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
