name: Tests
on:
  pull_request:
    branches:
      - v2
jobs:
  cypress-run:
    name: Integration tests
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: yarn
      - run: yarn integration-test
