name: Build and upload as release
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2-beta
        with:
          # Repository name with owner. For example, actions/checkout
          # Default: ${{ github.repository }}
          repository: ${{ github.repository }}

          # The branch, tag or SHA to checkout.  When checking out the repository that
          # triggered a workflow, this defaults to the reference or SHA for that event.
          # Otherwise, defaults to `master`.
          ref: 'test-git'
      - name: Build
        run: |
          npm install
          npm run-script build
  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2-beta
        with:
          # Repository name with owner. For example, actions/checkout
          # Default: ${{ github.repository }}
          repository: ${{ github.repository }}

          # The branch, tag or SHA to checkout.  When checking out the repository that
          # triggered a workflow, this defaults to the reference or SHA for that event.
          # Otherwise, defaults to `master`.
          ref: 'test-git'
      - name: Create release
        uses: Roang-zero1/github-create-release-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create GitHub release
        uses: Roang-zero1/github-upload-release-artifacts-action@master
        with:
          args:
            - ./build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
