name: Build and upload as release
on:
  push:
    branches:
      - test-git
jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          npm install
          npm run-script build
