name: Sentry

on:
  # manual trigger
  workflow_dispatch:

jobs:
  sentry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: yarn prepare
      - run: yarn build

      - name: Upload source maps to Sentry
        uses: getsentry/action-release@bd5f874fcda966ba48139b0140fb3ec0cb3aabdd 
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: production
          sourcemaps: './build/static/js'

