name: Build and upload as release
on:
  push:
    branches:
      - test-git
jobs:
release:
  name: Release
  runs-on: ubuntu-latest
  steps:
    - name: Release
      uses: fnkr/github-action-ghr@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GHR_COMPRESS: zip
        GHR_PATH: build/
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
